const { build } = require("./lib");
const OUT = process.argv[2];
const body = [
["title", "Service Agreement", "AI personal assistant · Month-to-month · Version 1.0 (September 2026)"],
["note", "**Translation.** This English version is provided for convenience. The French version was presented to the Client first and prevails, unless the Client ticks the language option in section 16.6."],
["h", "Between"],
["fields", [
  ["The provider", "[Legal name] doing business as **AI Staff**, NEQ [__________], [address], Montreal, Quebec. Email: hello@meetaistaff.com · Phone: +1 (438) 805-8804. Hereinafter “**AI Staff**”."],
  ["The client", "Legal name: ______________________________\nNEQ: ______________\nRepresented by: ______________________\nAddress: ________________________________\nEmail: ____________________\nPhone: ________________\nHereinafter the “**Client**”."],
]],
["note", "**In short (non-binding).** AI Staff configures and operates an AI assistant that answers your calls and messages and manages your calendar. It is month-to-month with no long-term contract: you can stop with 30 days' notice. Channels are activated in phases. AI can make mistakes; you keep oversight. Your data stays yours."],

["art", "Definitions"],
["c", "**Assistant**: the AI-based conversational agent configured by AI Staff for the Client (persona Sofía, Alex, Tomás or other)."],
["c", "**Service**: the configuration, hosting, operation and support of the Assistant, the phone number and the dashboard, according to the plan chosen in Schedule A."],
["c", "**Channels**: the means through which the Assistant communicates (calls, SMS, calendar, email, WhatsApp, social media direct messages, briefings)."],
["c", "**Client Data**: any information provided by the Client or its own customers in connection with the Service, including calls, messages, recordings, transcripts, appointments and contact details."],
["c", "**Personal Information**: any information that relates to a natural person and allows that person to be identified, within the meaning of the ~Act respecting the protection of personal information in the private sector~ (CQLR, c. P-39.1)."],

["art", "Purpose and contract documents"],
["c", "AI Staff provides the Service to the Client, who accepts it, on the terms of this agreement."],
["c", "The agreement includes **Schedule A** (order form: plan, price, channels), **Schedule B** (personal information processing agreement) and, if applicable, **Schedule C** (number porting authorization). In case of conflict, the order of precedence is: Schedule B, Schedule A, this agreement, Schedule C."],
["c", "The Client acts in the course of its business. This agreement is not a consumer contract."],

["art", "Description of the Service and phased rollout"],
["c", "Depending on the plan, the Assistant may: answer incoming calls, take messages, answer questions approved by the Client, offer and book appointments, send follow-up texts, transfer urgent calls and produce summaries in the dashboard."],
["c", "**Phased rollout: channels are activated in phases and confirmed during the discovery call.** At signature, the active channels are those checked in Schedule A. Any other channel (e.g., email, WhatsApp, direct messages, voice briefings) is activated only after written (email) confirmation from AI Staff."],
["c", "AI Staff does not guarantee any activation date for a channel. If a channel included in the plan is not yet available, the parties may agree in writing on a price adjustment."],
["c", "Outbound calls are limited to people who have an existing business relationship with the Client or who have consented (e.g., appointment reminders, follow-up on a request, the Client's own briefing). **The Service makes no unsolicited (“cold”) calls or messages.**"],

["art", "Setup, demo and go-live"],
["c", "Setup fees are set out in Schedule A (waived during the launch period, if applicable)."],
["c", "AI Staff prepares the configuration from information provided by the Client (onboarding questionnaire, website, services, hours, standard answers). The Client reviews and **approves the greeting, standard answers and transfer rules** before go-live."],
["c", "The Client grants the required access (e.g., calendar) through the authorization mechanisms offered by the relevant provider, never by sending passwords in clear text. The Client may revoke such access at any time."],

["art", "Phone number"],
["c", "The Client chooses one of the following options in Schedule A: **(a) porting** its existing number to AI Staff's platform; **(b) a new number** provided by AI Staff; or **(c) call forwarding** from its existing line to the Assistant's number."],
["c", "**Ported number (option a).** The Client remains the holder of the number. Porting depends on telecommunications carriers; AI Staff cannot guarantee its date. The Client signs Schedule C and provides the documents carriers require. At the end of the agreement, AI Staff will cooperate to port the number to the carrier of the Client's choice, upon written request received within 30 days after termination, provided amounts owing are paid."],
["c", "**New number (option b).** The number is assigned to the Client for the term of the agreement. At the end of the agreement, the Client may request that it be ported to another carrier within 30 days; after that period, the number may be released."],
["c", "**Call forwarding (option c).** The Client sets up and maintains forwarding with its own carrier and may cancel it at any time."],

["art", "Client obligations"],
["c", "Provide accurate, up-to-date information (services, prices, hours, policies) and inform AI Staff of any change."],
["c", "**Transparency toward its customers.** The Client agrees that the Assistant identifies itself as an AI assistant at the start of a conversation and announces that the call may be recorded. The Client never asks the Assistant to pretend to be a human."],
["c", "**Consent and applicable laws.** The Client is responsible for obtaining the consents required for commercial electronic messages (~Canada's Anti-Spam Legislation~), for complying with the CRTC Unsolicited Telecommunications Rules and the National Do Not Call List, and with the privacy laws that apply to its business."],
["c", "**Professional obligations.** If the Client practises a regulated profession (e.g., real estate brokerage (OACIQ), dentistry, health, law), it configures the Assistant so that it **gives no professional advice** and refers such questions to a qualified person. The Client remains solely responsible for its professional obligations."],
["c", "**Not an emergency service.** The Service does not replace 911 or any emergency service. The Assistant tells anyone in an emergency to dial 911."],
["c", "The Client does not use the Service for illegal, misleading, defamatory, discriminatory or harassing purposes, and does not attempt to circumvent the Service's security measures."],

["art", "Limits of artificial intelligence"],
["c", "The Client acknowledges that the Assistant relies on AI models that may misunderstand, make mistakes or give an incomplete answer. The Client regularly reviews the dashboard and reports any error so AI Staff can adjust the configuration."],
["c", "The Assistant makes no decision with a legal or significant effect on anyone. Sensitive or urgent situations, or those outside the approved rules, are transferred to the Client or logged for human follow-up."],
["c", "AI Staff does not guarantee any business result (number of customers, revenue, conversion rate)."],

["art", "Fees, taxes and payment"],
["c", "The Client pays the monthly price of the plan chosen in Schedule A, in Canadian dollars, **in advance on the first day of each monthly period**. The first month may be prorated."],
["c", "Prices exclude taxes. GST (5%) and QST (9.975%) are added. GST No.: [__________]  ·  QST No.: [__________]."],
["c", "Payment is by credit card or pre-authorized debit. Third-party fees expressly provided for in Schedule A (e.g., carrier porting fees, usage beyond the reasonable limits stated) are billed at cost, after notice to the Client."],
["c", "If payment is more than 15 days late after written notice, AI Staff may suspend the Service until payment. Unpaid amounts bear interest at [____]% per month."],
["c", "AI Staff may change its prices with **30 days' written notice**. A Client who refuses the change may terminate at no cost before the effective date."],

["art", "Term and termination"],
["c", "The agreement starts on the date of signature and renews automatically **month to month**, with no minimum term."],
["c", "Either party may terminate at any time with **30 days'** written notice (email). No penalty applies. Amounts paid for a month already begun are not refunded, unless otherwise agreed."],
["c", "Either party may terminate immediately by written notice if the other party commits a material breach and fails to remedy it within 10 days after written notice, or becomes insolvent. AI Staff may suspend the Service immediately in case of illegal use or a security threat."],
["c", "**At the end of the agreement**: (a) the Client may export its Data (CSV or JSON file) for 30 days; (b) AI Staff then destroys the Client Data, except data it must keep by law, and confirms it in writing on request; (c) section 5 applies to the number."],

["art", "Personal information"],
["c", "With respect to the Personal Information of the Client's customers, **AI Staff acts as a service provider** to the Client, who determines the purposes of its use. The parties' obligations are set out in Schedule B, which forms an integral part of the agreement."],
["c", "AI Staff processes the Client's own Personal Information (contact person, billing) in accordance with its privacy policy published at meetaistaff.com/confidentialite."],
["c", "AI Staff does not sell or rent any Personal Information and does not use Client Data to train AI models."],

["art", "Intellectual property"],
["c", "The Client remains the owner of its Data, trademarks and content. It grants AI Staff a non-exclusive licence, limited to the term of the agreement, to use them solely to provide the Service."],
["c", "AI Staff remains the owner of its platform, templates, configuration methods, dashboard and any general improvements to them."],
["c", "AI Staff uses the Client's name or logo for promotional purposes (e.g., a testimonial) only with its written consent."],

["art", "Confidentiality"],
["c", "Each party keeps the other party's non-public information confidential, uses it only to perform the agreement and discloses it only to people who need to know it and are bound by an equivalent obligation. This obligation survives 3 years after the end of the agreement (without limit for Personal Information)."],

["art", "Availability and third-party providers"],
["c", "AI Staff uses commercially reasonable efforts to keep the Service available at all times but does not guarantee uninterrupted or error-free operation. The Service depends on third-party providers (telephony, voice, AI models, hosting) and telecommunications networks."],
["c", "AI Staff may use subcontractors to provide the Service. The current list is published in its privacy policy. AI Staff remains responsible to the Client for performing its obligations."],
["c", "AI Staff notifies the Client within a reasonable time of any significant outage and of any planned maintenance likely to affect the Service."],

["art", "Liability"],
["c", "Except for intentional or gross fault, and except for bodily or moral injury, AI Staff's total liability under the agreement is limited to the amount paid by the Client for the Service during the **3 months** preceding the event giving rise to the claim."],
["c", "To the same extent, neither party is liable for indirect losses, including loss of profits, revenue, goodwill or data not directly resulting from its fault."],
["c", "The Client indemnifies AI Staff against any third-party claim arising from a breach of sections 6.2 to 6.6 (e.g., a message sent without consent, professional advice configured at the Client's request)."],

["art", "Force majeure"],
["c", "Neither party is liable for a delay or failure caused by superior force within the meaning of article 1470 of the ~Civil Code of Québec~, including a widespread outage of a telecommunications or cloud provider. The affected party notifies the other promptly."],

["art", "General provisions"],
["c", "**Notices.** Notices are validly given by email to the addresses above (for AI Staff: hello@meetaistaff.com)."],
["c", "**Entire agreement and amendments.** The agreement and its schedules are the entire agreement between the parties. Any amendment must be in writing (an email accepted by both parties)."],
["c", "**Assignment.** The Client may not assign the agreement without AI Staff's written consent, which may not be unreasonably withheld. AI Staff may assign it to an entity continuing its business, upon notice to the Client."],
["c", "**Electronic signature.** The agreement may be signed electronically and in counterparts, in accordance with the ~Act to establish a legal framework for information technology~."],
["c", "**Survival.** Sections 9.4, 10, 11, 12, 14 and 16 survive the end of the agreement."],
["c", "**Language.** This agreement was first presented to the Client in French. ☐ Having received the French version, the Client expressly chooses to be bound by this English version. ~(If this box is not checked, the French version prevails.)~"],
["c", "**Governing law.** The agreement is governed by the laws of Quebec and the federal laws of Canada applicable therein. The courts of the judicial district of Montreal have exclusive jurisdiction."],

["sig", [
  { title: "AI Staff", lines: ["By: Andrés Carreño", "Title: Founder"] },
  { title: "The Client", lines: ["By: ____________________________", "Title: ___________________________"] },
]],

["annex", "Schedule A · Order form", "Plan, price, channels and number. All prices in Canadian dollars, per month, plus taxes."],
["h", "1. Plan (check one)"],
["table", [
  ["", "Plan", "Price / month", "Includes"],
  ["☐", "**Essential**", "$397", "Dedicated number and 24/7 calls (FR, EN, ES), SMS, appointments in your calendar, private dashboard, calls to the assistant to ask for your reports"],
  ["☐", "**Pro**", "$597", "Everything in Essential + WhatsApp, scheduled calls from the assistant to you (up to 3 a day), unlimited calls (fair use)"],
  ["☐", "**Complete**", "$797", "Everything in Pro + Instagram and Facebook messages, social media stats, priority access"],
], { w: [6, 24, 16, 54], header: true }],
["fields", [
  ["Setup fee", "☐ $0 (launch offer)   ☐ $________"],
  ["Target go-live date", "________________ (indicative, not guaranteed)"],
  ["Reasonable usage limits", "________ call minutes / month; ________ SMS / month. Beyond: $________ / minute, $________ / SMS, after notice."],
  ["Payment method", "☐ Credit card   ☐ Pre-authorized debit"],
]],
["h", "2. Assistant"],
["fields", [
  ["Persona", "☐ Sofía   ☐ Alex   ☐ Tomás   ☐ Other: __________"],
  ["Languages", "________________________________________ (FR, EN, ES)"],
  ["Approved greeting", "________________________________________________"],
  ["Urgent transfers to", "Name: ______________   Phone: ______________"],
]],
["h", "3. Channels active at signature"],
["note", "Phased rollout: channels are activated in phases and confirmed during the discovery call."],
["table", [
  ["Channel", "Status at signature", "Activated on (confirmed by email)"],
  ["Incoming calls", "☐ Active", ""],
  ["SMS", "☐ Active", ""],
  ["Calendar (Google / Outlook / Apple / other)", "☐ Active", ""],
  ["WhatsApp", "☐ In phases", ""],
  ["Direct messages (Instagram / Facebook)", "☐ In phases", ""],
  ["Voice briefings (outbound call to the Client)", "☐ In phases", ""],
], { w: [42, 24, 34], header: true }],
["h", "4. Phone number"],
["check", [
  "**(a) Port** my existing number: (____) ____-______  →  complete Schedule C",
  "**(b) New number** provided by AI Staff (preferred area code: ______)",
  "**(c) Call forwarding** from my existing line to the Assistant's number",
]],
["sig", [
  { title: "AI Staff", lines: ["By: Andrés Carreño"] },
  { title: "The Client", lines: ["By: ____________________________"] },
]],

["annex", "Schedule B · Personal information processing agreement", "Service provider within the meaning of Quebec's Act respecting the protection of personal information in the private sector."],
["art", "Roles and purpose"],
["c", "The Client is responsible for the Personal Information of its own customers. AI Staff collects, uses and keeps it **on the Client's behalf and only on its instructions**, for the sole purpose of providing the Service."],
["c", "Categories of individuals: the Client's customers and prospects, people who contact the Client. Categories of information: name, phone number, email, content of calls and messages, recordings and transcripts, appointments, and any other information these people choose to share."],
["art", "AI Staff obligations"],
["c", "Use the information only for the Service; not sell, rent or use it to train AI models."],
["c", "Limit access to people who need it and are bound by confidentiality."],
["c", "Implement reasonable security measures given the sensitivity of the information: encryption in transit, per-client data separation, access control and revocation, no access keys in public code."],
["c", "Bind each subcontractor by a written agreement offering equivalent protection. Current list: Twilio (telephony, SMS, speech recognition and synthesis), Anthropic (language model), Make.com (automations), Supabase (database), Resend (email), and Google if the Client connects those services. AI Staff notifies the Client of any addition or replacement; the Client may object on reasonable grounds by terminating at no cost."],
["c", "**Transfers outside Quebec.** Some subcontractors process information outside Quebec (mainly in the United States). AI Staff has carried out a privacy impact assessment and provides it to the Client on request, to help it meet its own obligations."],
["c", "**Confidentiality incidents.** Notify the Client **without delay, and no later than 72 hours**, of any confidentiality incident affecting its information; take reasonable measures to reduce the risk of injury; provide the information the Client needs to assess the risk, keep its register and, where required, notify the Commission d'accès à l'information and the individuals concerned."],
["c", "Reasonably assist the Client in responding to its customers' requests for access, correction or withdrawal of consent, forwarding without delay any request received directly."],
["c", "At the end of the agreement, return or allow export of the information for 30 days, then securely destroy it, except as required by law."],
["c", "Provide the Client, on reasonable request, the information needed to demonstrate compliance with this schedule."],
["art", "Client obligations"],
["c", "Inform its customers, at the time of collection, that an AI assistant answers, that communications may be recorded and that information may be processed by a service provider, including outside Quebec (e.g., in its own privacy policy)."],
["c", "Give AI Staff lawful instructions and designate the person in charge of personal information in its business: Name: __________________  Email: __________________."],
["art", "Retention of recordings"],
["c", "Unless the Client instructs otherwise in writing, recordings and transcripts are kept for the term of the agreement and accessible in the dashboard. The Client may request a shorter period: ☐ 30 days  ☐ 90 days  ☐ 12 months  ☐ Term of the agreement."],

["annex", "Schedule C · Number porting authorization", "Complete only if the Client chooses option (a). Information must match the current carrier's bill exactly."],
["p", "I, the undersigned, authorize AI Staff and its telecommunications carriers to act on my behalf to port the number(s) below to their network. I confirm that I am the account holder or am authorized to act for the account holder. I understand that porting may end my current carrier's service for this number and that any fees or commitments with that carrier remain my responsibility."],
["fields", [
  ["Number(s) to port", ""],
  ["Current carrier", ""],
  ["Account holder name (as on the bill)", ""],
  ["Service address (as on the bill)", ""],
  ["Account number", ""],
  ["Port-out PIN (if required)", "Give it to AI Staff by phone only, never by unencrypted email."],
  ["Preferred date", "(indicative, not guaranteed)"],
]],
["note", "Attach a recent copy of the current carrier's bill (less than 30 days old). Do not cancel the current service before the port is confirmed."],
["sig", [
  { title: "Account holder", lines: ["Name: ____________________________"] },
  { title: "Received by AI Staff", lines: ["Name: ____________________________"] },
]],
];
build({ out: OUT, body, docTitle: "AI Staff — Service Agreement", short: "Service Agreement", footer: "AI Staff Service Agreement v1.0", artWord: "Section", pageWord: "page", initWord: "Initials", sigWord: "Signature", dateWord: "Date" });
