const { build } = require("./lib");
const [lang, OUT] = process.argv.slice(2);
const T = {
fr: { body: [
["title", "Entente de démonstration et de confidentialité", "Démo personnalisée gratuite et sans engagement · Version 1.0 (septembre 2026)"],
["fields", [
  ["Fournisseur", "[Nom légal] faisant affaire sous le nom **AI Staff**, Montréal (Québec) · hello@meetaistaff.com · +1 (438) 805-8804"],
  ["Prospect", "Nom : ____________________\nEntreprise : ____________________\nCourriel : ____________________\nTél. : ________________"],
]],
["note", "**En une phrase :** on vous prépare gratuitement une démo de votre adjointe IA avec vos informations publiques et vos réponses au questionnaire. Aucun mot de passe, aucun paiement, aucun engagement."],
["art", "Objet"],
["c", "AI Staff prépare une démonstration personnalisée de son Service (adjointe IA, tableau de bord) à partir : (a) des réponses du Prospect au questionnaire d'accueil (meetaistaff.com/onboarding); (b) de renseignements publics sur son entreprise (site web, fiche Google, pages publiques de réseaux sociaux)."],
["c", "La démo est **gratuite et sans engagement**. Elle ne crée aucune obligation d'achat pour le Prospect, ni d'obligation pour AI Staff de fournir un service."],
["art", "Ce que nous ne demandons pas"],
["c", "À cette étape, AI Staff **ne demande aucun mot de passe, aucun accès à des comptes, aucun renseignement de paiement** et ne transfère aucun numéro de téléphone. Le Prospect ne doit pas en transmettre."],
["c", "La démo utilise un numéro de démonstration d'AI Staff et des données d'exemple. Elle n'appelle ni n'écrit à aucun client du Prospect."],
["art", "Renseignements personnels"],
["c", "AI Staff utilise les renseignements fournis uniquement pour préparer la démo et communiquer avec le Prospect à ce sujet, conformément à sa politique de confidentialité (meetaistaff.com/confidentialite). Ils peuvent être traités par des fournisseurs situés hors du Québec, comme le décrit cette politique."],
["c", "Si le Prospect ne donne pas suite, les renseignements sont détruits au plus tard **12 mois** après la démo, ou plus tôt sur simple demande à hello@meetaistaff.com."],
["c", "Le Prospect ne reçoit des messages promotionnels que s'il y a consenti expressément; il peut se désabonner en tout temps."],
["art", "Confidentialité"],
["c", "AI Staff garde confidentielles les informations non publiques du Prospect (prix, volumes d'appels, processus internes) et ne les utilise que pour la démo."],
["c", "Le Prospect garde confidentiels les éléments non publics de la démo (configuration, scripts, prix spéciaux) et ne les communique pas à un concurrent d'AI Staff. Il peut les montrer à ses employés et conseillers."],
["c", "Ces obligations durent **2 ans** après la démo."],
["art", "Propriété et limites"],
["c", "AI Staff demeure propriétaire de la configuration, des scripts et du tableau de bord de démonstration. Le Prospect demeure propriétaire de son nom, de ses marques et de son contenu, qu'il autorise AI Staff à utiliser dans la démo seulement."],
["c", "La démo est fournie « telle quelle » à titre d'illustration. L'IA peut faire des erreurs. La démo ne constitue ni un conseil professionnel ni une garantie de résultat."],
["art", "Suite"],
["c", "Si le Prospect souhaite aller de l'avant, les parties signent le Contrat de service AI Staff. Le branchement du numéro (transfert, nouveau numéro ou renvoi d'appel) et l'activation des canaux se font seulement après cette signature, par phases."],
["c", "La présente entente est régie par les lois du Québec. Elle a été rédigée en français à la demande des parties. Elle peut être acceptée électroniquement, y compris en cochant la case prévue au questionnaire d'accueil."],
["sig", [
  { title: "AI Staff", lines: ["Par : Andrés Carreño"] },
  { title: "Le Prospect", lines: ["Par : ____________________________"] },
]],
], docTitle: "AI Staff — Entente de démonstration", short: "Entente de démonstration", footer: "Entente de démonstration AI Staff v1.0", artWord: "Article", pageWord: "page", initWord: "Initiales", sigWord: "Signature", dateWord: "Date" },
en: { body: [
["title", "Demo and Confidentiality Agreement", "Free, no-commitment personalized demo · Version 1.0 (September 2026)"],
["note", "**Translation.** The French version prevails unless the Prospect chooses this English version after receiving the French one."],
["fields", [
  ["Provider", "[Legal name] doing business as **AI Staff**, Montreal, Quebec · hello@meetaistaff.com · +1 (438) 805-8804"],
  ["Prospect", "Name: ____________________\nBusiness: ____________________\nEmail: ____________________\nPhone: ________________"],
]],
["note", "**In one sentence:** we build you a free demo of your AI assistant from your public information and your questionnaire answers. No passwords, no payment, no commitment."],
["art", "Purpose"],
["c", "AI Staff prepares a personalized demonstration of its Service (AI assistant, dashboard) based on: (a) the Prospect's answers to the onboarding questionnaire (meetaistaff.com/onboarding); (b) public information about its business (website, Google profile, public social media pages)."],
["c", "The demo is **free and without commitment**. It creates no obligation for the Prospect to buy, nor for AI Staff to provide any service."],
["art", "What we don't ask for"],
["c", "At this stage, AI Staff **asks for no passwords, no account access and no payment information**, and ports no phone number. The Prospect should not send any."],
["c", "The demo uses an AI Staff demo number and sample data. It does not call or message any of the Prospect's customers."],
["art", "Personal information"],
["c", "AI Staff uses the information provided only to prepare the demo and to contact the Prospect about it, in accordance with its privacy policy (meetaistaff.com/confidentialite). It may be processed by providers located outside Quebec, as that policy describes."],
["c", "If the Prospect does not proceed, the information is destroyed no later than **12 months** after the demo, or sooner on request to hello@meetaistaff.com."],
["c", "The Prospect receives promotional messages only with express consent and may unsubscribe at any time."],
["art", "Confidentiality"],
["c", "AI Staff keeps the Prospect's non-public information (prices, call volumes, internal processes) confidential and uses it only for the demo."],
["c", "The Prospect keeps the non-public elements of the demo (configuration, scripts, special pricing) confidential and does not share them with a competitor of AI Staff. It may show them to its employees and advisers."],
["c", "These obligations last **2 years** after the demo."],
["art", "Ownership and limits"],
["c", "AI Staff remains the owner of the demo configuration, scripts and dashboard. The Prospect remains the owner of its name, trademarks and content, which it authorizes AI Staff to use in the demo only."],
["c", "The demo is provided “as is” for illustration. AI can make mistakes. The demo is neither professional advice nor a guarantee of results."],
["art", "Next steps"],
["c", "If the Prospect wishes to proceed, the parties sign the AI Staff Service Agreement. Connecting the number (porting, new number or call forwarding) and activating channels happen only after that signature, in phases."],
["c", "This agreement is governed by the laws of Quebec. It may be accepted electronically, including by checking the box provided in the onboarding questionnaire."],
["sig", [
  { title: "AI Staff", lines: ["By: Andrés Carreño"] },
  { title: "The Prospect", lines: ["By: ____________________________"] },
]],
], docTitle: "AI Staff — Demo Agreement", short: "Demo Agreement", footer: "AI Staff Demo Agreement v1.0", artWord: "Section", pageWord: "page", initWord: "Initials", sigWord: "Signature", dateWord: "Date" },
};
build({ out: OUT, ...T[lang] });
