[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/andres"
  to = "/andres-carreno/"
  status = 301

[[redirects]]
  from = "/io"
  to = "/andres-carreno/#io"
  status = 302

[[headers]]
  for = "/andres-carreno/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/andres-carreno/libros/*"
  [headers.values]
    Content-Disposition = "attachment"
