# -*- coding: utf-8 -*-
"""Contenido de la página principal (sector "general"), en FR / EN / ES.
Se genera con tools/build_sectors.py usando la misma plantilla que las páginas de sector.
Los campos numéricos, íconos, integraciones y persona viven solo en FR (igual que en sectors_fr.py)."""

GEN = {}

GEN["fr"] = {
    "name": "AI Staff", "tab": "Général", "ic": "✨", "persona": "sofia",
    "aud": "les gens occupés et les petites entreprises",
    "title": "AI Staff — Votre adjointe personnelle IA",
    "desc": "Votre prochaine employée est une IA. Elle répond à vos appels et à vos textos jour et nuit et prend vos rendez-vous. À partir de 397 $ par mois.",
    "eyebrow": "Adjointe personnelle IA · Montréal",
    "h1": "Votre prochaine employée est <em>une IA.</em>",
    "lead": "{a} répond à vos appels et à vos textos jour et nuit et prend vos rendez-vous. Vous travaillez, {a} s'occupe du reste. En français, en anglais et en espagnol.",
    "trust": [["24/7", "jour, nuit et fins de semaine"], ["< 10 s", "pour décrocher"], ["FR · EN · ES", "la langue de vos clients"]],
    "script": [
        ["agent", "Déménagement Tremblay, bonsoir, c'est {a}. Comment puis-je vous aider?"],
        ["lead", "Bonjour, je voudrais une soumission pour un déménagement le 28."],
        ["agent", "Avec plaisir. Quelle est l'adresse de départ et d'arrivée, et combien de pièces?"],
        ["lead", "De Laval à Longueuil, un 4 et demi."],
        ["agent", "Parfait. Je note une visite jeudi à 10 h; l'équipe vous confirme par texto."],
        ["lead", "Super, merci!"],
        ["agent", "Avec plaisir. Bonne soirée!"],
    ],
    "ended": "Rendez-vous réservé ✓",
    "fcards": [["phone", "Appel manqué évité", "Soumission · Laval → Longueuil"], ["googlecalendar", "Visite réservée", "Jeudi 10 h · 4 ½"], ["sms", "Confirmation envoyée", "Texto au client"]],
    "painH": "Un appel manqué, c'est un client qui appelle ailleurs.",
    "painP": "Vous êtes au travail, en rendez-vous ou sur la route : le téléphone sonne et vous ne pouvez pas répondre. Le soir et la fin de semaine, personne ne répond. Le client appelle quelqu'un d'autre.",
    "does": ["Répond à vos appels jour et nuit, en français, en anglais et en espagnol", "Prend vos rendez-vous dans votre agenda", "Répond à vos textos et envoie les confirmations", "Résume chaque appel dans votre tableau de bord privé"],
    "features": [
        ["📞", "Appels 24/7", "Plus d'appel manqué, même le soir et la fin de semaine."],
        ["📅", "Votre agenda", "{a} propose vos plages libres et réserve directement."],
        ["💬", "Textos de suivi", "Confirmations et rappels envoyés pour vous."],
        ["🌎", "Dans la langue du client", "Français, anglais et espagnol."],
    ],
    "steps": [
        ["Le client appelle", "{a} décroche en moins de 10 secondes, jour ou nuit."],
        ["{a} comprend le besoin", "Qui appelle, pourquoi, adresse, disponibilités."],
        ["Le rendez-vous se réserve", "Dans votre agenda, avec confirmation par texto."],
        ["Vous recevez le résumé", "Chaque appel résumé dans votre tableau de bord."],
    ],
    "calc": {
        "mode": "human", "v": [40, 22, 0], "r": [[10, 60, 1], [15, 50, 1], [0, 0, 1]],
        "l1": "Heures à couvrir par semaine", "l2": "Salaire horaire", "l3": "",
        "eyebrow": "Faites le calcul", "title": "Combien coûte un employé qui répond au téléphone?",
        "lead": "Entrez les heures à couvrir et un salaire horaire : on compare avec {a}.",
        "cap": "par mois en salaire seulement, sans charges ni remplacements. {a} : dès {p} par mois, 24 h sur 24.",
        "note": "Calculé avec vos chiffres; les valeurs de départ ne sont que des exemples.",
        "disc": "Un employé couvre ses heures de travail. {a} couvre les 168 heures de la semaine.",
    },
    "stats": [["Appels répondus", "41", "cette semaine"], ["Messages traités", "58", "textos et appels"], ["Rendez-vous pris", "12", "↑ 3 cette semaine"], ["Temps libéré", "≈ 9 h", "estimation cette semaine"]],
    "calls": [
        ["Karim Benali", "Cette nuit · 23 h 48", "Soumission pour un déménagement, 4 ½ de Laval à Longueuil.", "hot", "Visite · jeudi 10 h"],
        ["Sophie Gagnon", "Hier · 16 h 40", "Veut déplacer son rendez-vous de vendredi.", "warm", "Rendez-vous déplacé · lundi 9 h"],
        ["Luis Ramírez", "Hier · 11 h 05", "Demande vos heures d'ouverture, en espagnol.", "new", "Réponse donnée en espagnol"],
    ],
    "ints": ["googlecalendar", "outlook", "gmail", "whatsapp", "instagram", "facebook", "google", "calendly", "stripe", "quickbooks"],
    "faq": [
        ["Est-ce que ça convient à mon métier?", "Si vos clients vous appellent, vous écrivent ou prennent rendez-vous, oui. On configure {a} avec vos services, vos heures et vos réponses. Il y a une page par secteur dans le menu."],
        ["Puis-je garder mon numéro?", "Oui. On peut transférer votre numéro actuel, vous en donner un nouveau, ou renvoyer vos appels vers {a}. Le transfert dépend de votre fournisseur et sa date ne peut pas être garantie."],
    ],
    "note": "<b>Transparence :</b> {a} se présente comme une assistante IA et annonce que l'appel peut être transcrit. Pour une urgence, {a} invite à composer le 911. Vous gardez la supervision et pouvez corriger ses réponses en tout temps.",
}

GEN["en"] = {
    "name": "AI Staff", "tab": "General", "aud": "busy people and small businesses",
    "title": "AI Staff — Your AI personal assistant",
    "desc": "Your next employee is an AI. She answers your calls and texts day and night and books your appointments. From $397 a month.",
    "eyebrow": "AI personal assistant · Montréal",
    "h1": "Your next employee is <em>an AI.</em>",
    "lead": "{a} answers your calls and texts day and night and books your appointments. You work; {a} handles the rest. In French, English and Spanish.",
    "trust": [["24/7", "day, night and weekends"], ["< 10 s", "to pick up"], ["FR · EN · ES", "your customers' language"]],
    "script": [
        ["agent", "Tremblay Moving, good evening, this is {a}. How can I help?"],
        ["lead", "Hi, I'd like a quote for a move on the 28th."],
        ["agent", "Happy to help. What are the pickup and drop-off addresses, and how many rooms?"],
        ["lead", "From Laval to Longueuil, a 2-bedroom."],
        ["agent", "Perfect. I'm noting a visit on Thursday at 10 AM; the team will confirm by text."],
        ["lead", "Great, thanks!"],
        ["agent", "My pleasure. Have a good evening!"],
    ],
    "ended": "Appointment booked ✓",
    "fcards": [["phone", "Missed call avoided", "Quote · Laval → Longueuil"], ["googlecalendar", "Visit booked", "Thursday 10 AM · 2-bedroom"], ["sms", "Confirmation sent", "Text to the customer"]],
    "painH": "A missed call is a customer calling someone else.",
    "painP": "You're at work, in a meeting or on the road: the phone rings and you can't answer. Evenings and weekends, nobody picks up. The customer calls someone else.",
    "does": ["Answers your calls day and night, in French, English and Spanish", "Books appointments in your calendar", "Answers your texts and sends confirmations", "Summarizes every call in your private dashboard"],
    "features": [
        ["📞", "Calls 24/7", "No more missed calls, even evenings and weekends."],
        ["📅", "Your calendar", "{a} offers your open slots and books directly."],
        ["💬", "Follow-up texts", "Confirmations and reminders sent for you."],
        ["🌎", "In your customer's language", "French, English and Spanish."],
    ],
    "steps": [
        ["The customer calls", "{a} picks up in under 10 seconds, day or night."],
        ["{a} understands the need", "Who's calling, why, address, availability."],
        ["The appointment is booked", "In your calendar, confirmed by text."],
        ["You get the summary", "Every call summarized in your dashboard."],
    ],
    "calc": {
        "l1": "Hours to cover per week", "l2": "Hourly wage", "l3": "",
        "eyebrow": "Do the math", "title": "What does an employee who answers the phone cost?",
        "lead": "Enter the hours to cover and an hourly wage: we compare with {a}.",
        "cap": "per month in wages alone, before payroll costs and replacements. {a}: from {p} a month, 24 hours a day.",
        "note": "Calculated from your numbers; the starting values are only examples.",
        "disc": "An employee covers working hours. {a} covers all 168 hours of the week.",
    },
    "stats": [["Calls answered", "41", "this week"], ["Messages handled", "58", "texts and calls"], ["Appointments booked", "12", "↑ 3 this week"], ["Time freed", "≈ 9 h", "estimate this week"]],
    "calls": [
        ["Karim Benali", "Last night · 11:48 PM", "Quote for a move, 2-bedroom from Laval to Longueuil.", "hot", "Visit · Thursday 10 AM"],
        ["Sophie Gagnon", "Yesterday · 4:40 PM", "Wants to move her Friday appointment.", "warm", "Appointment moved · Monday 9 AM"],
        ["Luis Ramírez", "Yesterday · 11:05 AM", "Asks for your opening hours, in Spanish.", "new", "Answered in Spanish"],
    ],
    "faq": [
        ["Will it work for my line of business?", "If your customers call you, text you or book appointments, yes. We set up {a} with your services, hours and answers. There's a page per industry in the menu."],
        ["Can I keep my number?", "Yes. We can port your current number, give you a new one, or forward your calls to {a}. Porting depends on your carrier and its date can't be guaranteed."],
    ],
    "note": "<b>Transparency:</b> {a} introduces itself as an AI assistant and says the call may be transcribed. For an emergency, {a} tells callers to dial 911. You keep oversight and can correct the answers at any time.",
}

GEN["es"] = {
    "name": "AI Staff", "tab": "General", "aud": "personas ocupadas y pequeños negocios",
    "title": "AI Staff — Tu asistente personal con IA",
    "desc": "Tu próxima empleada es una IA. Contesta tus llamadas y tus mensajes de texto de día y de noche y agenda tus citas. Desde 397 $ al mes.",
    "eyebrow": "Asistente personal con IA · Montreal",
    "h1": "Tu próxima empleada es <em>una IA.</em>",
    "lead": "{a} contesta tus llamadas y tus mensajes de texto de día y de noche y agenda tus citas. Tú trabajas, {a} se ocupa del resto. En francés, inglés y español.",
    "trust": [["24/7", "día, noche y fines de semana"], ["< 10 s", "para contestar"], ["FR · EN · ES", "el idioma de tus clientes"]],
    "script": [
        ["agent", "Mudanzas Tremblay, buenas noches, habla {a}. ¿En qué puedo ayudarle?"],
        ["lead", "Hola, quisiera una cotización para una mudanza el día 28."],
        ["agent", "Con gusto. ¿Cuáles son la dirección de salida y la de llegada, y cuántas habitaciones?"],
        ["lead", "De Laval a Longueuil, un apartamento de dos habitaciones."],
        ["agent", "Perfecto. Anoto una visita el jueves a las 10; el equipo le confirma por mensaje de texto."],
        ["lead", "¡Genial, gracias!"],
        ["agent", "Con gusto. ¡Buenas noches!"],
    ],
    "ended": "Cita agendada ✓",
    "fcards": [["phone", "Llamada perdida evitada", "Cotización · Laval → Longueuil"], ["googlecalendar", "Visita agendada", "Jueves 10 h · 2 habitaciones"], ["sms", "Confirmación enviada", "Texto al cliente"]],
    "painH": "Una llamada perdida es un cliente que llama a otro.",
    "painP": "Estás trabajando, en una cita o en la carretera: el teléfono suena y no puedes contestar. De noche y los fines de semana nadie responde. El cliente llama a otro lado.",
    "does": ["Contesta tus llamadas de día y de noche, en francés, inglés y español", "Agenda las citas en tu calendario", "Responde tus mensajes de texto y envía las confirmaciones", "Resume cada llamada en tu dashboard privado"],
    "features": [
        ["📞", "Llamadas 24/7", "Cero llamadas perdidas, incluso de noche y en fin de semana."],
        ["📅", "Tu agenda", "{a} ofrece tus horarios libres y agenda directamente."],
        ["💬", "Textos de seguimiento", "Confirmaciones y recordatorios enviados por ti."],
        ["🌎", "En el idioma del cliente", "Francés, inglés y español."],
    ],
    "steps": [
        ["El cliente llama", "{a} contesta en menos de 10 segundos, de día o de noche."],
        ["{a} entiende lo que necesita", "Quién llama, para qué, dirección, disponibilidad."],
        ["Se agenda la cita", "En tu calendario, con confirmación por texto."],
        ["Recibes el resumen", "Cada llamada resumida en tu dashboard."],
    ],
    "calc": {
        "l1": "Horas por cubrir a la semana", "l2": "Salario por hora", "l3": "",
        "eyebrow": "Haz la cuenta", "title": "¿Cuánto cuesta un empleado que contesta el teléfono?",
        "lead": "Escribe las horas por cubrir y un salario por hora: lo comparamos con {a}.",
        "cap": "al mes solo en salario, sin cargas ni reemplazos. {a}: desde {p} al mes, las 24 horas.",
        "note": "Calculado con tus cifras; los valores iniciales son solo ejemplos.",
        "disc": "Un empleado cubre su horario de trabajo. {a} cubre las 168 horas de la semana.",
    },
    "stats": [["Llamadas atendidas", "41", "esta semana"], ["Mensajes atendidos", "58", "textos y llamadas"], ["Citas agendadas", "12", "↑ 3 esta semana"], ["Tiempo liberado", "≈ 9 h", "estimación esta semana"]],
    "calls": [
        ["Karim Benali", "Anoche · 23:48", "Cotización de mudanza, dos habitaciones de Laval a Longueuil.", "hot", "Visita · jueves 10 h"],
        ["Sophie Gagnon", "Ayer · 16:40", "Quiere mover su cita del viernes.", "warm", "Cita movida · lunes 9 h"],
        ["Luis Ramírez", "Ayer · 11:05", "Pregunta por tu horario de atención, en español.", "new", "Respondido en español"],
    ],
    "faq": [
        ["¿Sirve para mi oficio?", "Si tus clientes te llaman, te escriben o agendan citas, sí. Configuramos a {a} con tus servicios, tus horarios y tus respuestas. En el menú hay una página por sector."],
        ["¿Puedo conservar mi número?", "Sí. Podemos transferir tu número actual, darte uno nuevo o desviar tus llamadas a {a}. La transferencia depende de tu operador y no se puede garantizar su fecha."],
    ],
    "note": "<b>Transparencia:</b> {a} se presenta como asistente de IA y avisa que la llamada puede transcribirse. Ante una emergencia, {a} indica marcar el 911. Tú mantienes la supervisión y puedes corregir sus respuestas en cualquier momento.",
}
