# -*- coding: utf-8 -*-
# Textes communs à toutes les pages sectorielles (FR / EN / ES). {a} = assistante, {aud} = public du secteur.
G = {
"fr": {
 "nav.demo": "Démo", "nav.pricing": "Tarifs", "nav.faq": "FAQ", "nav.sectors": "Secteurs", "nav.cta": "📞 Parler à {a}", "nav.home": "Accueil",
 "hero.pick": "Choisissez votre adjointe :", "hero.cta1": "Réserver ma démo", "hero.cta2": "📞 Parler à {a}",
 "p.sofia": "voix féminine", "p.alex": "voix neutre", "p.tomas": "voix masculine",
 "phone.idle": "Appel entrant · démo", "phone.call": "▶ Écouter un appel", "phone.connecting": "{a} décroche…", "phone.live": "En ligne · appel en cours", "phone.hangup": "Raccrocher", "phone.hint": "ligne démo — appelez pour vrai",
 "pain.k": "Le problème", "does.k": "Ce que {a} fait pour vous",
 "feat.eyebrow": "Conçu pour votre métier", "feat.title": "Pensé pour {aud}.",
 "calc.eyebrow": "Faites le calcul", "calc.title": "Combien vous coûtent les appels manqués?", "calc.lead": "Déplacez les curseurs avec vos chiffres — l'estimation se met à jour toute seule.",
 "calc.cap": "de revenus potentiels manqués par mois, selon vos chiffres.", "calc.note": "Estimation indicative calculée à partir de vos propres données. Vos résultats réels dépendent de votre marché et de votre pratique.",
 "how.eyebrow": "Comment ça marche", "how.title": "De l'appel au rendez-vous, sans toucher votre téléphone.",
 "dash.eyebrow": "Ce que vous verrez chaque matin", "dash.title": "Votre tableau de bord.", "dash.lead": "Chaque appel est transcrit, résumé et suivi d'une prochaine action.", "dash.badge": "◆ Données de démonstration", "dash.more": "Voir le tableau de bord complet →", "dash.sub": "avec {a} · AI Staff Exécutive", "dash.name": "Votre entreprise", "dash.next": "Prochaine action",
 "int.eyebrow": "Intégrations", "int.title": "Avec les outils que vous utilisez déjà.", "int.note": "Connexions via nos automatisations sécurisées, activées selon votre plan et confirmées lors de l'appel découverte. Les marques citées appartiennent à leurs propriétaires.",
 "price.eyebrow": "Tarifs", "price.title": "Une fraction du prix d'une réceptionniste.", "price.lead": "Commencez par l'essentiel. Ajoutez des canaux quand vous êtes prêt.", "price.per": "/ mois", "price.feat": "Recommandé",
 "priceTop": ["CAD · mois par mois", "Sans contrat", "Installation gratuite au lancement"],
 "rollout": "Déploiement progressif : les canaux s'activent par phases et sont confirmés avec vous lors de l'appel découverte.",
 "faq.eyebrow": "Questions fréquentes", "faq.title": "Ce qu'on nous demande.",
 "faqGen": [["Y a-t-il un humain derrière?", "Oui. Notre équipe à Montréal configure {a} selon vos instructions et supervise son travail. Quand une demande sort du cadre prévu, {a} prend le message et un humain prend le relais."], ["Quelles langues parle {a}?", "Le français, l'anglais et l'espagnol, et bien d'autres langues selon votre plan (3, jusqu'à 5, ou toutes). {a} détecte la langue de l'appelant et répond dans la même."], ["Y a-t-il un contrat?", "Non. C'est mois par mois, sans engagement. L'installation est gratuite pendant le lancement."]],
 "final.title": "Le prochain appel ne doit pas se perdre.", "final.lead": "15 minutes pour voir ce que {a} ferait pour votre entreprise.", "final.cta1": "Réserver ma démo", "final.cta2": "📞 Appeler {a}",
 "footer.tag": "l'adjointe personnelle IA, à Montréal", "footer.line": "◆ les tableaux de bord de cette page utilisent des données d'exemple",
 "sticky.demo": "Réserver ma démo", "sticky.call": "📞 {a}",
 "prM.title": "Excellent choix", "prM.lead": "Écrivez-nous : on planifie ensemble votre appel découverte et votre activation.", "prM.cta": "Nous écrire", "prM.later": "Peut-être plus tard",
 "tags": {"hot": "Chaud", "warm": "Tiède", "cold": "Froid", "new": "Nouveau"},
 "your": {"f": "Votre adjointe : ", "m": "Votre adjoint : ", "n": "Votre adjoint·e : "},
 "plans": [
  {"name": "Assistante", "tag": "L'essentiel : vos appels et vos rendez-vous, pris en charge.", "price": 997, "cta": "Choisir Assistante", "feat": ["Appels 24/7", "Prise et confirmation de rendez-vous", "Réponses par texto (SMS)", "3 langues au choix (ex. FR · EN · ES)", "Tableau de bord et résumés d'appels", "1 briefing par jour au téléphone"]},
  {"name": "Exécutive", "tag": "Tous vos canaux, et une adjointe qui organise votre journée.", "price": 1497, "cta": "Choisir Exécutive", "featured": True, "feat": ["Tout le plan Assistante, plus :", "WhatsApp et DM Instagram / Facebook", "Courriel unifié avec brouillons à approuver", "Jusqu'à 5 langues", "Jusqu'à 3 briefings par jour", "Appelez {a} quand vous voulez", "Appels de suivi sortants à vos clients"]},
  {"name": "Dédiée", "tag": "Votre propre instance, sur mesure, avec supervision prioritaire.", "price": 2497, "cta": "Choisir Dédiée", "feat": ["Tout le plan Exécutive, plus :", "Toutes les langues disponibles", "Instance cloud privée et dédiée", "Intégrations sur mesure", "Supervision humaine prioritaire", "Ligne téléphonique locale dédiée"]}]
},
"en": {
 "nav.demo": "Demo", "nav.pricing": "Pricing", "nav.faq": "FAQ", "nav.sectors": "Industries", "nav.cta": "📞 Talk to {a}", "nav.home": "Home",
 "hero.pick": "Pick your assistant:", "hero.cta1": "Book my demo", "hero.cta2": "📞 Talk to {a}",
 "p.sofia": "female voice", "p.alex": "neutral voice", "p.tomas": "male voice",
 "phone.idle": "Incoming call · demo", "phone.call": "▶ Play a call", "phone.connecting": "{a} is picking up…", "phone.live": "Live · call in progress", "phone.hangup": "Hang up", "phone.hint": "demo line — call it for real",
 "pain.k": "The problem", "does.k": "What {a} does for you",
 "feat.eyebrow": "Built for your trade", "feat.title": "Designed for {aud}.",
 "calc.eyebrow": "Do the math", "calc.title": "What do missed calls cost you?", "calc.lead": "Move the sliders with your numbers — the estimate updates live.",
 "calc.cap": "in potential revenue missed per month, based on your numbers.", "calc.note": "Indicative estimate computed from your own data. Actual results depend on your market and your practice.",
 "how.eyebrow": "How it works", "how.title": "From call to appointment, without touching your phone.",
 "dash.eyebrow": "What you'll see every morning", "dash.title": "Your dashboard.", "dash.lead": "Every call is transcribed, summarized and paired with a next action.", "dash.badge": "◆ Demo data", "dash.more": "See the full dashboard →", "dash.sub": "with {a} · AI Staff Executive", "dash.name": "Your business", "dash.next": "Next action",
 "int.eyebrow": "Integrations", "int.title": "With the tools you already use.", "int.note": "Connections run through our secure automations, enabled according to your plan and confirmed on the discovery call. Brands shown belong to their owners.",
 "price.eyebrow": "Pricing", "price.title": "A fraction of the cost of a receptionist.", "price.lead": "Start with the essentials. Add channels when you're ready.", "price.per": "/ month", "price.feat": "Recommended",
 "priceTop": ["CAD · month to month", "No contract", "Free setup during launch"],
 "rollout": "Progressive rollout: channels are enabled in phases and confirmed with you on the discovery call.",
 "faq.eyebrow": "FAQ", "faq.title": "What people ask us.",
 "faqGen": [["Is there a human behind it?", "Yes. Our team in Montréal configures {a} to your instructions and supervises the work. When a request falls outside the plan, {a} takes a message and a human takes over."], ["Which languages does {a} speak?", "French, English and Spanish, plus many more depending on your plan (3, up to 5, or all). {a} detects the caller's language and answers in it."], ["Is there a contract?", "No. It's month to month, no commitment. Setup is free during launch."]],
 "final.title": "The next call shouldn't be lost.", "final.lead": "15 minutes to see what {a} would do for your business.", "final.cta1": "Book my demo", "final.cta2": "📞 Call {a}",
 "footer.tag": "the AI personal assistant, from Montréal", "footer.line": "◆ dashboards on this page use sample data",
 "sticky.demo": "Book my demo", "sticky.call": "📞 {a}",
 "prM.title": "Great choice", "prM.lead": "Email us and we'll plan your discovery call and activation together.", "prM.cta": "Email us", "prM.later": "Maybe later",
 "tags": {"hot": "Hot", "warm": "Warm", "cold": "Cold", "new": "New"},
 "your": {"f": "Your assistant: ", "m": "Your assistant: ", "n": "Your assistant: "},
 "plans": [
  {"name": "Assistant", "tag": "The essentials: your calls and appointments, handled.", "price": 997, "cta": "Choose Assistant", "feat": ["24/7 calls", "Appointment booking and confirmations", "Text message (SMS) replies", "3 languages of your choice (e.g. FR · EN · ES)", "Dashboard and call summaries", "1 phone briefing per day"]},
  {"name": "Executive", "tag": "Every channel, plus an assistant who runs your day.", "price": 1497, "cta": "Choose Executive", "featured": True, "feat": ["Everything in Assistant, plus:", "WhatsApp and Instagram / Facebook DMs", "Unified email with drafts to approve", "Up to 5 languages", "Up to 3 briefings per day", "Call {a} whenever you want", "Outbound follow-up calls to your clients"]},
  {"name": "Dedicated", "tag": "Your own instance, custom-built, with priority supervision.", "price": 2497, "cta": "Choose Dedicated", "feat": ["Everything in Executive, plus:", "Every available language", "Private, dedicated cloud instance", "Custom integrations", "Priority human supervision", "Dedicated local phone line"]}]
},
"es": {
 "nav.demo": "Demo", "nav.pricing": "Precios", "nav.faq": "FAQ", "nav.sectors": "Sectores", "nav.cta": "📞 Hablar con {a}", "nav.home": "Inicio",
 "hero.pick": "Elige tu asistente:", "hero.cta1": "Agendar mi demo", "hero.cta2": "📞 Hablar con {a}",
 "p.sofia": "voz femenina", "p.alex": "voz neutra", "p.tomas": "voz masculina",
 "phone.idle": "Llamada entrante · demo", "phone.call": "▶ Escuchar una llamada", "phone.connecting": "{a} está contestando…", "phone.live": "En línea · llamada en curso", "phone.hangup": "Colgar", "phone.hint": "línea demo — llama de verdad",
 "pain.k": "El problema", "does.k": "Lo que {a} hace por ti",
 "feat.eyebrow": "Hecho para tu oficio", "feat.title": "Pensado para {aud}.",
 "calc.eyebrow": "Haz la cuenta", "calc.title": "¿Cuánto te cuestan las llamadas perdidas?", "calc.lead": "Mueve los controles con tus cifras — la estimación se actualiza sola.",
 "calc.cap": "en ingresos potenciales perdidos al mes, según tus cifras.", "calc.note": "Estimación indicativa calculada con tus propios datos. Los resultados reales dependen de tu mercado y tu práctica.",
 "how.eyebrow": "Cómo funciona", "how.title": "De la llamada a la cita, sin tocar tu teléfono.",
 "dash.eyebrow": "Lo que verás cada mañana", "dash.title": "Tu panel.", "dash.lead": "Cada llamada queda transcrita, resumida y con una próxima acción.", "dash.badge": "◆ Datos de demostración", "dash.more": "Ver el panel completo →", "dash.sub": "con {a} · AI Staff Ejecutiva", "dash.name": "Tu negocio", "dash.next": "Próxima acción",
 "int.eyebrow": "Integraciones", "int.title": "Con las herramientas que ya usas.", "int.note": "Conexiones mediante nuestras automatizaciones seguras, activadas según tu plan y confirmadas en la llamada de descubrimiento. Las marcas mencionadas pertenecen a sus dueños.",
 "price.eyebrow": "Precios", "price.title": "Una fracción de lo que cuesta una recepcionista.", "price.lead": "Empieza con lo esencial. Agrega canales cuando estés listo.", "price.per": "/ mes", "price.feat": "Recomendado",
 "priceTop": ["CAD · mes a mes", "Sin contrato", "Instalación gratis en el lanzamiento"],
 "rollout": "Despliegue progresivo: los canales se activan por fases y se confirman contigo en la llamada de descubrimiento.",
 "faq.eyebrow": "Preguntas frecuentes", "faq.title": "Lo que nos preguntan.",
 "faqGen": [["¿Hay un humano detrás?", "Sí. Nuestro equipo en Montreal configura a {a} según tus instrucciones y supervisa su trabajo. Si algo se sale de sus instrucciones, {a} toma el mensaje y un humano retoma."], ["¿Qué idiomas habla {a}?", "Francés, inglés y español, y muchos más según tu plan (3, hasta 5 o todos). {a} detecta el idioma de quien llama y responde en el mismo."], ["¿Hay contrato?", "No. Es mes a mes, sin compromiso. La instalación es gratis durante el lanzamiento."]],
 "final.title": "La próxima llamada no debería perderse.", "final.lead": "15 minutos para ver lo que {a} haría por tu negocio.", "final.cta1": "Agendar mi demo", "final.cta2": "📞 Llamar a {a}",
 "footer.tag": "la asistente personal con IA, desde Montreal", "footer.line": "◆ los paneles de esta página usan datos de ejemplo",
 "sticky.demo": "Agendar mi demo", "sticky.call": "📞 {a}",
 "prM.title": "Excelente elección", "prM.lead": "Escríbenos y planificamos juntos tu llamada de descubrimiento y tu activación.", "prM.cta": "Escríbenos", "prM.later": "Quizás después",
 "tags": {"hot": "Caliente", "warm": "Tibio", "cold": "Frío", "new": "Nuevo"},
 "your": {"f": "Tu asistente: ", "m": "Tu asistente: ", "n": "Tu asistente: "},
 "plans": [
  {"name": "Asistente", "tag": "Lo esencial: tus llamadas y tus citas, atendidas.", "price": 997, "cta": "Elegir Asistente", "feat": ["Llamadas 24/7", "Agenda y confirmación de citas", "Respuestas por SMS", "3 idiomas a elección (ej. FR · EN · ES)", "Panel y resúmenes de llamadas", "1 briefing por llamada al día"]},
  {"name": "Ejecutiva", "tag": "Todos tus canales, y una asistente que organiza tu día.", "price": 1497, "cta": "Elegir Ejecutiva", "featured": True, "feat": ["Todo el plan Asistente, más:", "WhatsApp y DMs de Instagram / Facebook", "Correo unificado con borradores para aprobar", "Hasta 5 idiomas", "Hasta 3 briefings al día", "Llama a {a} cuando quieras", "Llamadas de seguimiento salientes a tus clientes"]},
  {"name": "Dedicada", "tag": "Tu propia instancia, a medida, con supervisión prioritaria.", "price": 2497, "cta": "Elegir Dedicada", "feat": ["Todo el plan Ejecutiva, más:", "Todos los idiomas disponibles", "Instancia cloud privada y dedicada", "Integraciones a medida", "Supervisión humana prioritaria", "Línea telefónica local dedicada"]}]
}
}
