# -*- coding: utf-8 -*-
# Textes communs à toutes les pages sectorielles (FR / EN / ES). {a} = assistante, {aud} = public du secteur.
G = {
"fr": {
 "nav.demo": "Démo", "nav.pricing": "Tarifs", "nav.faq": "FAQ", "nav.sectors": "Secteurs", "nav.cta": "📞 Parler à {a}", "nav.home": "Accueil",
 "hero.pick": "Choisissez votre adjointe :", "hero.cta1": "Réserver ma démo", "hero.cta2": "📞 Parler à {a}",
 "p.sofia": "voix féminine", "p.alex": "voix neutre", "p.tomas": "voix masculine",
 "phone.idle": "Appel entrant · démo", "phone.call": "▶ Écouter un appel", "phone.connecting": "{a} décroche…", "phone.live": "En ligne · appel en cours", "phone.hangup": "Raccrocher", "phone.hint": "ligne démo — appelez pour vrai",
 "pain.k": "Le problème", "does.k": "Ce que {a} fait pour vous",
 "feat.eyebrow": "Conçu pour votre métier", "feat.title": "Pensé pour {aud}.",
 "calc.eyebrow": "Faites le calcul", "calc.title": "Combien vous coûtent les appels manqués?", "calc.lead": "Déplacez les curseurs avec vos chiffres — l'estimation se met à jour toute seule.",
 "calc.cap": "de revenus potentiels manqués par mois, selon vos chiffres.", "calc.note": "Estimation indicative calculée à partir de vos propres données. Vos résultats réels dépendent de votre marché et de votre pratique.",
 "how.eyebrow": "Comment ça marche", "how.title": "De l'appel au rendez-vous, sans toucher votre téléphone.",
 "dash.eyebrow": "Ce que vous verrez chaque matin", "dash.title": "Votre tableau de bord.", "dash.lead": "Chaque appel est transcrit, résumé et suivi d'une prochaine action.", "dash.badge": "◆ Données de démonstration", "dash.more": "Voir le tableau de bord complet →", "dash.sub": "avec {a} · AI Staff", "dash.name": "Votre entreprise", "dash.next": "Prochaine action",
 "int.eyebrow": "Intégrations", "int.title": "Avec les outils que vous utilisez déjà.", "int.note": "Connexions via nos automatisations sécurisées, activées selon votre plan et confirmées lors de l'appel découverte. Les marques citées appartiennent à leurs propriétaires.",
 "price.eyebrow": "Tarifs", "price.title": "Une fraction du prix d'une réceptionniste.", "price.lead": "Une adjointe humaine coûte environ 3 500 à 4 500 $ par mois (estimation). Choisissez ce dont vous avez besoin.", "price.per": "/ mois", "price.feat": "Recommandé",
 "priceTop": ["CAD · mois par mois · taxes en sus", "Sans contrat", "Installation gratuite au lancement"],
 "rollout": "Déploiement progressif : les canaux s'activent par phases et sont confirmés avec vous lors de l'appel découverte.",
 "faq.eyebrow": "Questions fréquentes", "faq.title": "Ce qu'on nous demande.",
 "faqGen": [["Qui configure {a}?", "Nous préparons la configuration selon vos instructions, et vous pouvez corriger les réponses en tout temps. Quand une demande sort du cadre prévu, {a} prend le message pour que vous puissiez rappeler."], ["Quelles langues parle {a}?", "Le français, l'anglais et l'espagnol. {a} détecte la langue de l'appelant et répond dans la même."], ["Y a-t-il un contrat?", "Non. C'est mois par mois, sans engagement. L'installation est gratuite pendant le lancement."]],
 "final.title": "Le prochain appel ne doit pas se perdre.", "final.lead": "15 minutes pour voir ce que {a} ferait pour votre entreprise.", "final.cta1": "Réserver ma démo", "final.cta2": "📞 Appeler {a}",
 "footer.tag": "l'adjointe personnelle IA, à Montréal", "footer.line": "◆ les tableaux de bord de cette page utilisent des données d'exemple",
 "sticky.demo": "Réserver ma démo", "sticky.call": "📞 {a}",
 "prM.title": "Excellent choix", "prM.lead": "Écrivez-nous : on planifie ensemble votre appel découverte et votre activation.", "prM.cta": "Nous écrire", "prM.later": "Peut-être plus tard",
 "tags": {"hot": "Chaud", "warm": "Tiède", "cold": "Froid", "new": "Nouveau"},
 "your": {"f": "Votre adjointe : ", "m": "Votre adjoint : ", "n": "Votre adjoint·e : "},
 "plans": [{"name": "Essentiel", "tag": "Vos appels, vos textos et votre agenda, pris en charge.", "price": 397, "cta": "Choisir Essentiel", "feat": ["Numéro de téléphone dédié et appels 24/7", "Français, anglais et espagnol", "Réponses par texto (SMS)", "Rendez-vous pris dans votre agenda", "Tableau de bord privé", "Appelez {a} pour demander vos rapports (par phases)"]}, {"name": "Pro", "tag": "L'essentiel, plus WhatsApp et des appels programmés.", "price": 597, "cta": "Choisir Pro", "feat": ["Tout le plan Essentiel, plus :", "WhatsApp avec le même numéro (par phases)", "{a} vous appelle aux heures que vous choisissez, jusqu'à 3 fois par jour (par phases)", "Appelez {a} à toute heure", "Appels illimités, usage raisonnable"]}, {"name": "Complet", "tag": "Tous vos canaux, avec un accès prioritaire.", "price": 797, "cta": "Choisir Complet", "feat": ["Tout le plan Pro, plus :", "Messages Instagram et Facebook (par phases)", "Statistiques de vos réseaux sociaux (par phases)", "Accès prioritaire : vos questions et changements passent en premier"]}]
},
"en": {
 "nav.demo": "Demo", "nav.pricing": "Pricing", "nav.faq": "FAQ", "nav.sectors": "Industries", "nav.cta": "📞 Talk to {a}", "nav.home": "Home",
 "hero.pick": "Pick your assistant:", "hero.cta1": "Book my demo", "hero.cta2": "📞 Talk to {a}",
 "p.sofia": "female voice", "p.alex": "neutral voice", "p.tomas": "male voice",
 "phone.idle": "Incoming call · demo", "phone.call": "▶ Play a call", "phone.connecting": "{a} is picking up…", "phone.live": "Live · call in progress", "phone.hangup": "Hang up", "phone.hint": "demo line — call it for real",
 "pain.k": "The problem", "does.k": "What {a} does for you",
 "feat.eyebrow": "Built for your trade", "feat.title": "Designed for {aud}.",
 "calc.eyebrow": "Do the math", "calc.title": "What do missed calls cost you?", "calc.lead": "Move the sliders with your numbers — the estimate updates live.",
 "calc.cap": "in potential revenue missed per month, based on your numbers.", "calc.note": "Indicative estimate computed from your own data. Actual results depend on your market and your practice.",
 "how.eyebrow": "How it works", "how.title": "From call to appointment, without touching your phone.",
 "dash.eyebrow": "What you'll see every morning", "dash.title": "Your dashboard.", "dash.lead": "Every call is transcribed, summarized and paired with a next action.", "dash.badge": "◆ Demo data", "dash.more": "See the full dashboard →", "dash.sub": "with {a} · AI Staff", "dash.name": "Your business", "dash.next": "Next action",
 "int.eyebrow": "Integrations", "int.title": "With the tools you already use.", "int.note": "Connections run through our secure automations, enabled according to your plan and confirmed on the discovery call. Brands shown belong to their owners.",
 "price.eyebrow": "Pricing", "price.title": "A fraction of the cost of a receptionist.", "price.lead": "A human assistant costs roughly $3,500 to $4,500 a month (estimate). Choose what you need.", "price.per": "/ month", "price.feat": "Recommended",
 "priceTop": ["CAD · month to month · plus taxes", "No contract", "Free setup during launch"],
 "rollout": "Progressive rollout: channels are enabled in phases and confirmed with you on the discovery call.",
 "faq.eyebrow": "FAQ", "faq.title": "What people ask us.",
 "faqGen": [["Who sets up {a}?", "We prepare the configuration to your instructions, and you can correct the answers at any time. When a request falls outside the plan, {a} takes a message so you can call back."], ["Which languages does {a} speak?", "French, English and Spanish. {a} detects the caller's language and answers in the same one."], ["Is there a contract?", "No. It's month to month, no commitment. Setup is free during launch."]],
 "final.title": "The next call shouldn't be lost.", "final.lead": "15 minutes to see what {a} would do for your business.", "final.cta1": "Book my demo", "final.cta2": "📞 Call {a}",
 "footer.tag": "the AI personal assistant, from Montréal", "footer.line": "◆ dashboards on this page use sample data",
 "sticky.demo": "Book my demo", "sticky.call": "📞 {a}",
 "prM.title": "Great choice", "prM.lead": "Email us and we'll plan your discovery call and activation together.", "prM.cta": "Email us", "prM.later": "Maybe later",
 "tags": {"hot": "Hot", "warm": "Warm", "cold": "Cold", "new": "New"},
 "your": {"f": "Your assistant: ", "m": "Your assistant: ", "n": "Your assistant: "},
 "plans": [{"name": "Essential", "tag": "Your calls, texts and calendar, handled.", "price": 397, "cta": "Choose Essential", "feat": ["Dedicated phone number and 24/7 calls", "French, English and Spanish", "Text message (SMS) replies", "Appointments booked in your calendar", "Private dashboard", "Call {a} to ask for your reports (in phases)"]}, {"name": "Pro", "tag": "The essentials, plus WhatsApp and scheduled calls.", "price": 597, "cta": "Choose Pro", "feat": ["Everything in Essential, plus:", "WhatsApp on the same number (in phases)", "{a} calls you at the times you choose, up to 3 times a day (in phases)", "Call {a} any time", "Unlimited calls, fair use"]}, {"name": "Complete", "tag": "Every channel, with priority access.", "price": 797, "cta": "Choose Complete", "feat": ["Everything in Pro, plus:", "Instagram and Facebook messages (in phases)", "Social media stats (in phases)", "Priority access: your questions and changes come first"]}]
},
"es": {
 "nav.demo": "Demo", "nav.pricing": "Precios", "nav.faq": "FAQ", "nav.sectors": "Sectores", "nav.cta": "📞 Hablar con {a}", "nav.home": "Inicio",
 "hero.pick": "Elige tu asistente:", "hero.cta1": "Agendar mi demo", "hero.cta2": "📞 Hablar con {a}",
 "p.sofia": "voz femenina", "p.alex": "voz neutra", "p.tomas": "voz masculina",
 "phone.idle": "Llamada entrante · demo", "phone.call": "▶ Escuchar una llamada", "phone.connecting": "{a} está contestando…", "phone.live": "En línea · llamada en curso", "phone.hangup": "Colgar", "phone.hint": "línea demo — llama de verdad",
 "pain.k": "El problema", "does.k": "Lo que {a} hace por ti",
 "feat.eyebrow": "Hecho para tu oficio", "feat.title": "Pensado para {aud}.",
 "calc.eyebrow": "Haz la cuenta", "calc.title": "¿Cuánto te cuestan las llamadas perdidas?", "calc.lead": "Mueve los controles con tus cifras — la estimación se actualiza sola.",
 "calc.cap": "en ingresos potenciales perdidos al mes, según tus cifras.", "calc.note": "Estimación indicativa calculada con tus propios datos. Los resultados reales dependen de tu mercado y tu práctica.",
 "how.eyebrow": "Cómo funciona", "how.title": "De la llamada a la cita, sin tocar tu teléfono.",
 "dash.eyebrow": "Lo que verás cada mañana", "dash.title": "Tu panel.", "dash.lead": "Cada llamada queda transcrita, resumida y con una próxima acción.", "dash.badge": "◆ Datos de demostración", "dash.more": "Ver el panel completo →", "dash.sub": "con {a} · AI Staff", "dash.name": "Tu negocio", "dash.next": "Próxima acción",
 "int.eyebrow": "Integraciones", "int.title": "Con las herramientas que ya usas.", "int.note": "Conexiones mediante nuestras automatizaciones seguras, activadas según tu plan y confirmadas en la llamada de descubrimiento. Las marcas mencionadas pertenecen a sus dueños.",
 "price.eyebrow": "Precios", "price.title": "Una fracción de lo que cuesta una recepcionista.", "price.lead": "Una asistente humana cuesta alrededor de 3 500 a 4 500 $ al mes (estimación). Elige lo que necesitas.", "price.per": "/ mes", "price.feat": "Recomendado",
 "priceTop": ["CAD · mes a mes · más impuestos", "Sin contrato", "Instalación gratis en el lanzamiento"],
 "rollout": "Despliegue progresivo: los canales se activan por fases y se confirman contigo en la llamada de descubrimiento.",
 "faq.eyebrow": "Preguntas frecuentes", "faq.title": "Lo que nos preguntan.",
 "faqGen": [["¿Quién configura a {a}?", "Nosotros preparamos la configuración según tus instrucciones y puedes corregir las respuestas en cualquier momento. Si algo se sale de lo previsto, {a} toma el mensaje para que puedas devolver la llamada."], ["¿Qué idiomas habla {a}?", "Francés, inglés y español. {a} detecta el idioma de quien llama y responde en el mismo."], ["¿Hay contrato?", "No. Es mes a mes, sin compromiso. La instalación es gratis durante el lanzamiento."]],
 "final.title": "La próxima llamada no debería perderse.", "final.lead": "15 minutos para ver lo que {a} haría por tu negocio.", "final.cta1": "Agendar mi demo", "final.cta2": "📞 Llamar a {a}",
 "footer.tag": "la asistente personal con IA, desde Montreal", "footer.line": "◆ los paneles de esta página usan datos de ejemplo",
 "sticky.demo": "Agendar mi demo", "sticky.call": "📞 {a}",
 "prM.title": "Excelente elección", "prM.lead": "Escríbenos y planificamos juntos tu llamada de descubrimiento y tu activación.", "prM.cta": "Escríbenos", "prM.later": "Quizás después",
 "tags": {"hot": "Caliente", "warm": "Tibio", "cold": "Frío", "new": "Nuevo"},
 "your": {"f": "Tu asistente: ", "m": "Tu asistente: ", "n": "Tu asistente: "},
 "plans": [{"name": "Esencial", "tag": "Tus llamadas, tus mensajes de texto y tu agenda, atendidos.", "price": 397, "cta": "Elegir Esencial", "feat": ["Número de teléfono propio y llamadas 24/7", "Francés, inglés y español", "Respuestas por mensaje de texto (SMS)", "Citas agendadas en tu calendario", "Dashboard privado", "Llama a {a} para pedirle tus reportes (por fases)"]}, {"name": "Pro", "tag": "Lo esencial, más WhatsApp y llamadas programadas.", "price": 597, "cta": "Elegir Pro", "feat": ["Todo el plan Esencial, más:", "WhatsApp con el mismo número (por fases)", "{a} te llama a las horas que elijas, hasta 3 veces al día (por fases)", "Llama a {a} a cualquier hora", "Llamadas ilimitadas, uso razonable"]}, {"name": "Completo", "tag": "Todos tus canales, con acceso prioritario.", "price": 797, "cta": "Elegir Completo", "feat": ["Todo el plan Pro, más:", "Mensajes de Instagram y Facebook (por fases)", "Estadísticas de tus redes sociales (por fases)", "Acceso prioritario: tus preguntas y cambios van primero"]}]
}
}
