# -*- coding: utf-8 -*-
# Texto ES de las páginas sectoriales. Los valores numéricos, íconos e integraciones vienen del FR.
ES = {
"immobilier": {
 "name": "Courtiers inmobiliarios", "tab": "Courtiers inmobiliarios", "aud": "los courtiers inmobiliarios",
 "title": "AI Staff — El asistente personal con IA de los courtiers inmobiliarios de Quebec",
 "desc": "Alex contesta durante tus visitas, precalifica a los compradores, propone visitas y te llama cada mañana con tu día.",
 "eyebrow": "Para courtiers inmobiliarios de Quebec",
 "h1": "Estás en una visita. <em>{a} atiende a los compradores.</em>",
 "lead": "{a} contesta durante tus visitas, firmas y días libres, precalifica al comprador, propone la visita en tu agenda — y te llama a las 7:30 con tus visitas, leads calientes y seguimientos.",
 "trust": [["24/7", "incluso durante tus visitas"], ["7:30", "tu briefing de la mañana"], ["FR · EN", "y el idioma de tus clientes"]],
 "script": [["agent", "Oficina de Marie, buenos días, habla {a}. ¿En qué le puedo ayudar?"], ["lead", "Hola, vi la propiedad en Saint-Urbain. ¿Sigue disponible?"], ["agent", "¡Sí! Dos habitaciones, 850 pi², en 649 000 $. ¿Está preaprobado y por qué monto?"], ["lead", "Sí, hasta 700 000 $."], ["agent", "Perfecto, encaja bien. Marie tiene libre mañana a las 14:00 o a las 16:00 para una visita."], ["lead", "A las 16:00, perfecto."], ["agent", "Confirmado para mañana a las 16:00. Le envío la confirmación por mensaje."]],
 "ended": "Visita confirmada ✓",
 "fcards": [["phone", "Lead precalificado", "Preaprobado 700 k$ · Plateau"], ["googlecalendar", "Visita confirmada", "482, rue Saint-Urbain · 16:00"], ["gmail", "Borrador listo", "Ficha de la propiedad · por aprobar"]],
 "painH": "Estás en una visita. Un comprador llama… al siguiente courtier.",
 "painP": "Noches, fines de semana, firmas: tu teléfono nunca descansa, y cada llamada perdida es un comprador que encuentra otro courtier en Centris.",
 "does": ["Contesta durante tus visitas y precalifica: presupuesto, preaprobación, zona, plazos", "Propone visitas en tu agenda y envía las confirmaciones", "Prepara correos de seguimiento y fichas de propiedades para que los apruebes", "Te llama a las 7:30 con tus visitas, leads calientes y seguimientos"],
 "features": [["🏠", "Precalificación", "Presupuesto, preaprobación, zona y plazos: devuelves la llamada sabiendo todo del caso."], ["📅", "Visitas", "Horarios propuestos según tu agenda, con confirmación y recordatorio al comprador."], ["☀️", "Briefing de la mañana", "Tus visitas del día, los leads de la noche y los seguimientos, por teléfono."], ["📲", "Llama a {a}", "«Confirma la visita de las 16:00 con Sophie»: listo, sin abrir ninguna app."]],
 "steps": [["El comprador llama", "Mientras enseñas una casa, {a} contesta."], ["{a} precalifica", "Presupuesto, preaprobación, zona, plazos."], ["Se propone la visita", "En tu agenda, con confirmación por mensaje."], ["Tú cierras", "Resumen, transcripción y próxima acción en tu panel."]],
 "calc": {"l1": "Llamadas perdidas por semana", "l2": "Tus visitas cierran al", "l3": "Comisión promedio", "disc": "Una llamada perdida no es solo una llamada: es un comprador llamando al siguiente courtier en Centris."},
 "stats": [["Llamadas atendidas", "63", "↑ 8 esta semana"], ["Leads precalificados", "32", "↑ 8 esta semana"], ["Visitas confirmadas", "11", "↑ 3 esta semana"], ["Briefings", "7", "cada mañana a las 7:30"]],
 "calls": [["Julie Tanguay", "Hoy · 9:12", "Busca 3 habitaciones cerca de Villeray, preaprobada hasta 650 000 $.", "hot", "Visita propuesta · mié. 16:00"], ["Philippe Bergeron", "Ayer · 16:47", "Vende en Verdun, quiere una valuación antes de listar.", "warm", "Enviar el reporte de valuación"], ["Mei Kwan", "Ayer · 11:03", "Explora el mercado del Plateau, sin planes inmediatos.", "cold", "Seguimiento en 30 días"]],
 "faq": [["¿{a} da consejos de corretaje?", "Nunca. {a} precalifica, toma el mensaje y propone la visita. Cualquier pregunta de corretaje te llega a ti: mantienes tu juicio profesional y el control de tus expedientes."], ["¿{a} habla de verdad francés e inglés?", "Sí: {a} detecta el idioma de quien llama y continúa en francés, inglés o español, con vocabulario adaptado al sector inmobiliario de Quebec."], ["¿Puedo llamar a {a} yo mismo?", "Sí, con el plan Completo: {a} reconoce tu número. Pide tu agenda de mañana o que confirme una visita."]],
 "note": "<b>Cumplimiento OACIQ:</b> {a} nunca da consejos de corretaje ni reemplaza tu juicio profesional. Cada interacción se transcribe y archiva: mantienes el control de tus expedientes y comunicaciones con clientes, como exigen tus obligaciones deontológicas."
},
"cvc": {
 "name": "Calefacción y climatización (HVAC)", "tab": "HVAC", "aud": "las empresas de calefacción y climatización",
 "title": "AI Staff — Asistente con IA para empresas de calefacción y climatización (HVAC)",
 "desc": "Urgencias 24/7, mantenimientos de temporada, presupuestos: la asistente con IA que contesta mientras tus técnicos están en la calle.",
 "eyebrow": "Para empresas de HVAC de Quebec",
 "h1": "¿Sin calefacción a las 2 de la mañana? <em>{a} contesta.</em>",
 "lead": "{a} atiende urgencias 24/7, clasifica lo que no puede esperar, agenda tus mantenimientos y presupuestos — y te llama en la mañana con tu día. En francés, inglés y el idioma de tus clientes.",
 "trust": [["24/7", "incluso en plena ola de frío"], ["< 10 s", "para contestar"], ["Urgente", "pasado al técnico de guardia"]],
 "script": [["agent", "Calefacción Lavoie, buenas noches, habla {a}. ¿En qué le puedo ayudar?"], ["lead", "Mi calefactor no enciende y hace 14 grados en la casa."], ["agent", "Entiendo. ¿Siente olor a gas? ¿Hay niños o personas mayores en la casa?"], ["lead", "No huele a nada. Sí, dos niños."], ["agent", "De acuerdo, es prioritario. Aviso ahora mismo al técnico de guardia con su dirección."], ["lead", "Gracias, de verdad."], ["agent", "Él le devuelve la llamada en los próximos minutos. Le envío la confirmación por mensaje."]],
 "ended": "Urgencia enviada al técnico ✓",
 "fcards": [["phone", "Urgencia · Pierrefonds", "Calefactor averiado · técnico avisado"], ["googlecalendar", "Mantenimiento agendado", "Bomba de calor · jueves 10:00"], ["sms", "Recordatorios enviados", "Cambio de filtro · 42 clientes"]],
 "painH": "En invierno, cada llamada perdida es un cliente que llama a la competencia.",
 "painP": "Durante las olas de frío el teléfono no para. Tus técnicos están en la calle, la oficina está saturada y las urgencias se mezclan con las solicitudes de presupuesto.",
 "does": ["Contesta 24/7 e identifica las urgencias reales (sin calefacción, fuga, olor a gas)", "Pasa lo urgente al técnico de guardia, con la dirección y el contexto", "Agenda mantenimientos anuales, instalaciones y visitas de presupuesto", "Envía recordatorios de mantenimiento y cambio de filtro"],
 "features": [["🚨", "Clasificación de urgencias", "Preguntas de seguridad, nivel de prioridad y traspaso inmediato al técnico correcto."], ["🗓️", "Mantenimientos de temporada", "Recordatorios antes de la temporada: calefactores en otoño, aires y bombas de calor en primavera."], ["🧾", "Presupuestos", "Tipo de equipo, superficie, fotos por mensaje: la visita queda agendada y el expediente listo."], ["🌎", "En el idioma del cliente", "Francés, inglés, español y más: cada cliente es atendido en su idioma."]],
 "steps": [["El cliente llama", "De día, de noche o en tormenta: {a} contesta en menos de 10 segundos."], ["{a} califica", "Urgencia o no, tipo de equipo, dirección, disponibilidad."], ["Se agenda la cita", "En el horario de tus técnicos, con confirmación por mensaje."], ["Recibes el resumen", "Cada mañana: urgencias de la noche, visitas del día, presupuestos pendientes."]],
 "calc": {"l1": "Llamadas perdidas por semana", "l2": "Tasa de conversión en trabajo", "l3": "Valor promedio de un trabajo", "disc": "Una urgencia sin respuesta no vuelve a llamar: llama a la siguiente empresa en Google."},
 "stats": [["Llamadas atendidas", "37", "esta semana"], ["Urgencias enviadas", "6", "promedio 4 min"], ["Visitas agendadas", "14", "↑ 5 esta semana"], ["Presupuestos pendientes", "5", "expedientes completos"]],
 "calls": [["Julie Tremblay", "Anoche · 2:14", "Calefactor averiado, dos niños. Enviado al técnico de guardia.", "hot", "Visita de urgencia · 7:30"], ["Marc Gagnon", "Ayer · 16:40", "Presupuesto para una bomba de calor mural, casa de 1 400 pi².", "warm", "Visita de presupuesto · jueves 13:00"], ["Nadia Roy", "Ayer · 11:05", "Mantenimiento anual del aire acondicionado central.", "new", "Mantenimiento agendado · 3 oct. 9:00"]],
 "faq": [["¿{a} puede hacer un diagnóstico técnico?", "No. {a} hace las preguntas correctas (equipo, síntomas, seguridad) y las pasa al técnico, sin dar nunca un diagnóstico ni instrucciones de reparación. Si hay olor a gas, {a} pide salir de la casa y llamar al 911."], ["¿Cómo me llegan las urgencias?", "Según tus reglas: llamada directa al técnico de guardia, mensaje con la dirección y el resumen, o ambos. Lo demás espera tu briefing de la mañana."], ["¿Se gestionan los mantenimientos de temporada?", "Sí: {a} llama a tus clientes antes de la temporada, ofrece horarios y llena la agenda de tus técnicos."]],
 "note": "<b>Seguridad:</b> {a} nunca da diagnósticos técnicos. Si hay olor a gas o peligro, {a} pide salir del lugar y llamar al 911, y luego avisa a tu equipo."
},
"paysagement": {
 "name": "Paisajismo y jardinería", "tab": "Paisajismo", "aud": "los paisajistas",
 "title": "AI Staff — Asistente con IA para paisajistas y jardinería",
 "desc": "Presupuestos, visitas de estimación, contratos de mantenimiento: la asistente con IA que contesta mientras tus equipos trabajan.",
 "eyebrow": "Para paisajistas de Quebec",
 "h1": "Estás en una obra. <em>{a} toma los presupuestos.</em>",
 "lead": "En primavera, las solicitudes llegan todas a la vez. {a} contesta, toma los detalles del terreno, agenda las visitas de estimación y hace seguimiento — mientras tus equipos trabajan.",
 "trust": [["24/7", "incluso el fin de semana"], ["< 10 s", "para contestar"], ["Fotos", "pedidas por mensaje"]],
 "script": [["agent", "Paisajismo Vert-Nord, buenos días, habla {a}. ¿En qué le puedo ayudar?"], ["lead", "Quisiera un presupuesto para adoquines y un jardín de flores."], ["agent", "Con gusto. ¿Cuál es la dirección y más o menos cuántos pies cuadrados? Le envío un mensaje para recibir unas fotos."], ["lead", "En Laval, unos 400 pies cuadrados."], ["agent", "Perfecto. Nuestro estimador puede pasar el martes a las 17:00 o el sábado a las 10:00."], ["lead", "El sábado a las 10."], ["agent", "Queda agendado. Recibirá una confirmación y un recordatorio el día anterior."]],
 "ended": "Visita de estimación agendada ✓",
 "fcards": [["phone", "Presupuesto · Laval", "Adoquines 400 pi² · fotos recibidas"], ["googlecalendar", "Estimación agendada", "Sábado 10:00 · Sainte-Rose"], ["sms", "Seguimientos enviados", "12 presupuestos pendientes"]],
 "painH": "Llega la primavera, y el teléfono suena mientras tienes las manos en la tierra.",
 "painP": "Las solicitudes de presupuesto se acumulan en el buzón de voz. Los que no reciben respuesta el mismo día firman con otra empresa.",
 "does": ["Contesta las solicitudes de presupuesto, incluso en tus días más ocupados", "Pide la dirección, la superficie y fotos por mensaje", "Agenda las visitas de estimación en el horario del estimador", "Hace seguimiento a los clientes que no respondieron al presupuesto"],
 "features": [["📐", "Presupuestos completos", "Dirección, tipo de proyecto, superficie, presupuesto y fotos: el estimador llega preparado."], ["🔁", "Contratos de mantenimiento", "Corte de césped, mantenimiento de temporada, apertura y cierre: recordatorios y renovaciones."], ["⛅", "Clima y aplazamientos", "Tus clientes reciben un mensaje cuando un día se aplaza por la lluvia."], ["❄️", "¿Y en invierno?", "¿También quitas nieve? El mismo número pasa a los contratos de invierno."]],
 "steps": [["El cliente llama o escribe", "Teléfono, mensaje, Facebook o Instagram: {a} responde en todas partes."], ["{a} prepara el presupuesto", "Detalles del proyecto, fotos y disponibilidad."], ["Se agenda la visita", "En el horario del estimador, con recordatorio el día anterior."], ["Firmas más contratos", "Los presupuestos pendientes reciben seguimiento automático."]],
 "calc": {"l1": "Solicitudes perdidas por semana", "l2": "Tasa de firma", "l3": "Valor promedio de un proyecto", "disc": "En primavera, la primera empresa que devuelve la llamada suele quedarse con el contrato."},
 "stats": [["Solicitudes recibidas", "29", "esta semana"], ["Estimaciones agendadas", "11", "↑ 4 esta semana"], ["Presupuestos con seguimiento", "12", "3 firmados"], ["Fotos recibidas", "47", "por mensaje"]],
 "calls": [["Sophie Bélanger", "Hoy · 8:12", "Adoquines y jardín de flores, unos 400 pi², Laval.", "hot", "Estimación · sábado 10:00"], ["Karim Haddad", "Ayer · 19:30", "Contrato de corte de césped para la temporada, terreno de esquina.", "warm", "Presupuesto enviado · seguimiento viernes"], ["Denis Pelletier", "Ayer · 13:02", "Poda de dos arces, no es urgente.", "new", "Llamada programada · lunes"]],
 "faq": [["¿{a} da precios por teléfono?", "Solo si tú quieres: puedes dar una lista de precios base (ej. corte semanal). Para proyectos, {a} toma los detalles y agenda la visita de estimación."], ["¿Cómo se reciben las fotos?", "Por mensaje: el cliente responde con sus fotos, que quedan adjuntas a su solicitud en tu panel."], ["¿Y en invierno?", "Si también quitas nieve, el mismo número sirve para los contratos de invierno. Mira la página de Remoción de nieve."]],
 "note": ""
},
"deneigement": {
 "name": "Remoción de nieve", "tab": "Remoción de nieve", "aud": "las empresas de remoción de nieve",
 "title": "AI Staff — Asistente con IA para empresas de remoción de nieve",
 "desc": "Tormenta de nieve: todas las llamadas atendidas, entradas olvidadas reportadas, contratos de temporada vendidos.",
 "eyebrow": "Para empresas de remoción de nieve",
 "h1": "¿Tormenta de nieve? <em>{a} toma todas las llamadas.</em>",
 "lead": "El día después de una tormenta, todos llaman al mismo tiempo. {a} atiende a cada cliente, reporta las entradas olvidadas, tranquiliza y vende tus contratos de temporada — en francés, inglés y el idioma de tus clientes.",
 "trust": [["Varias", "llamadas a la vez, sin buzón de voz"], ["24/7", "incluso a las 5 de la mañana"], ["SMS", "alertas antes y después de la tormenta"]],
 "script": [["agent", "Remoción de nieve Boréal, buenos días, habla {a}."], ["lead", "¡No limpiaron mi entrada y tengo que irme a trabajar!"], ["agent", "Disculpe la espera. ¿Cuál es su dirección?"], ["lead", "245, rue des Érables, en Longueuil."], ["agent", "Gracias. Reporto su dirección como prioridad al equipo de Longueuil."], ["lead", "Perfecto, gracias."], ["agent", "Le envío un mensaje en cuanto el equipo vaya en camino."]],
 "ended": "Dirección reportada al equipo ✓",
 "fcards": [["phone", "Entrada olvidada · Longueuil", "Reportada al equipo como prioridad"], ["sms", "Alerta de tormenta enviada", "Todos los clientes avisados"], ["stripe", "Contrato de temporada pagado", "Brossard · 2 pagos"]],
 "painH": "El día después de una tormenta, tu teléfono está saturado.",
 "painP": "Clientes preocupados, entradas olvidadas, contratos nuevos: todo llega a la vez, muchas veces antes del amanecer. Un cliente sin respuesta no renueva el invierno siguiente.",
 "does": ["Contesta todas las llamadas, incluso cuando llegan al mismo tiempo", "Anota las entradas olvidadas y las reporta al equipo correcto", "Vende y renueva contratos de temporada, con enlace de pago", "Envía alertas de tormenta y de paso por mensaje"],
 "features": [["📍", "Entradas olvidadas", "Dirección, zona y urgencia: enviadas al equipo correcto en segundos."], ["📝", "Contratos de temporada", "Precio según el tamaño de la entrada, enlace de pago y recordatorios de cuotas."], ["📣", "Alertas a clientes", "Un mensaje a tus clientes antes y después de la tormenta: menos llamadas, clientes tranquilos."], ["🔁", "Renovaciones", "Al final del verano, {a} llama a tus clientes para renovar antes de la primera nevada."]],
 "steps": [["Llega la tormenta", "{a} avisa a tus clientes por mensaje."], ["Entran las llamadas", "Cada llamada recibe respuesta, incluso a las 5 de la mañana."], ["Los problemas se reportan", "Entradas olvidadas y quejas van al equipo correcto."], ["Se venden contratos", "Clientes nuevos y renovaciones, con pago en línea."]],
 "calc": {"l1": "Llamadas perdidas por semana (en invierno)", "l2": "Tasa de conversión en contrato", "l3": "Valor promedio de un contrato de temporada", "disc": "Un cliente que no pudo comunicarse durante una tormenta rara vez renueva el invierno siguiente."},
 "stats": [["Llamadas atendidas", "186", "durante la tormenta"], ["Entradas reportadas", "14", "todas resueltas"], ["Contratos vendidos", "9", "↑ 3 esta semana"], ["Alertas enviadas", "412", "por mensaje"]],
 "calls": [["Chantal Morin", "Esta mañana · 5:48", "Entrada olvidada, debe salir a trabajar a las 7. Longueuil.", "hot", "Reportada al equipo · prioridad"], ["Ahmed Benali", "Ayer · 20:15", "Nuevo contrato de temporada, entrada doble en Brossard.", "new", "Contrato enviado · 2 pagos"], ["Lise Fortin", "Ayer · 9:30", "Pregunta si la acera está incluida.", "warm", "Respuesta enviada · cliente tranquilo"]],
 "faq": [["¿Y si todos llaman al mismo tiempo?", "{a} puede atender varias llamadas simultáneas, sin fila de espera ni buzón de voz. La capacidad se ajusta a tu volumen durante la activación."], ["¿{a} conoce mis zonas y mis equipos?", "Sí: defines tus zonas y a quién contactar en cada una. Las entradas olvidadas se envían al equipo correcto por mensaje."], ["¿Se pueden vender contratos en línea?", "Sí: {a} explica tus paquetes, envía un enlace de pago (Stripe o Square) y confirma el contrato."]],
 "note": ""
},
"garages": {
 "name": "Talleres mecánicos", "tab": "Talleres", "aud": "los talleres mecánicos",
 "title": "AI Staff — Asistente con IA para talleres mecánicos",
 "desc": "Citas, temporada de llantas, «¿ya está mi carro?»: la asistente con IA que contesta mientras tus mecánicos trabajan.",
 "eyebrow": "Para talleres mecánicos",
 "h1": "¿Las manos en un motor? <em>{a} agenda la cita.</em>",
 "lead": "{a} contesta mientras tus mecánicos trabajan: citas, cambios de llantas, solicitudes de estimación, seguimiento de reparaciones — y avisa por mensaje cuando el vehículo está listo.",
 "trust": [["24/7", "incluso en la noche y el fin de semana"], ["< 10 s", "para contestar"], ["SMS", "cuando el vehículo está listo"]],
 "script": [["agent", "Taller Beaulieu, buenos días, habla {a}."], ["lead", "Quisiera que me pongan las llantas de invierno."], ["agent", "Claro. ¿Qué vehículo tiene, y ya tiene sus llantas?"], ["lead", "Un Honda Civic 2019, tengo mis llantas."], ["agent", "Perfecto. Tengo el miércoles a las 8:00 o el jueves a las 15:30."], ["lead", "El jueves a las 15:30."], ["agent", "Anotado. Le envío la confirmación y un recordatorio el día anterior."]],
 "ended": "Cita de llantas agendada ✓",
 "fcards": [["phone", "Cambio de llantas · Civic 2019", "Jueves 15:30 · confirmado"], ["sms", "Vehículo listo", "Mensaje enviado al Sr. Girard"], ["googlecalendar", "Agenda del taller", "3 bahías libres mañana temprano"]],
 "painH": "La temporada de llantas son cientos de llamadas en pocas semanas.",
 "painP": "Mientras tus mecánicos trabajan, nadie puede contestar. Los clientes cuelgan, y los que esperan su vehículo llaman para saber si ya está listo.",
 "does": ["Agenda citas según la disponibilidad de tus bahías y mecánicos", "Gestiona la temporada de llantas: cambio, almacenamiento, recordatorios", "Responde «¿Ya está mi carro?» y avisa por mensaje cuando lo está", "Toma solicitudes de estimación con el vehículo y los síntomas"],
 "features": [["🛞", "Temporada de llantas", "Recordatorios antes de la fecha límite, citas en ráfaga, almacenamiento anotado."], ["🔔", "Vehículo listo", "Un mensaje al cliente cuando el vehículo está listo: menos llamadas al taller."], ["🧰", "Solicitudes de estimación", "Marca, modelo, año, síntomas: el mecánico sabe qué esperar."], ["🛡️", "Sin diagnósticos", "{a} nunca da diagnósticos mecánicos: la información va al mecánico."]],
 "steps": [["El cliente llama", "{a} contesta, incluso con el taller lleno."], ["{a} identifica la necesidad", "Vehículo, servicio pedido, urgencia."], ["Se agenda la cita", "Según tus bahías y mecánicos."], ["El cliente queda informado", "Confirmación, recordatorio y mensaje cuando está listo."]],
 "calc": {"l1": "Llamadas perdidas por semana", "l2": "Tasa de conversión en citas", "l3": "Factura promedio", "disc": "Un cliente que cae en el buzón de voz llama al taller de al lado."},
 "stats": [["Llamadas atendidas", "52", "esta semana"], ["Citas agendadas", "23", "14 de llantas"], ["«¿Ya está?»", "18", "respondidos sin ti"], ["Mensajes «listo»", "21", "enviados"]],
 "calls": [["Luc Roy", "Hoy · 7:55", "Cambio a llantas de invierno, Honda Civic 2019, llantas propias.", "new", "Cita · jueves 15:30"], ["Amina Diallo", "Ayer · 17:20", "Ruido en los frenos delanteros, Toyota RAV4 2017.", "hot", "Inspección · mañana 8:00"], ["Paul Girard", "Ayer · 12:10", "Pregunta si su vehículo está listo.", "warm", "Mensaje enviado · listo a las 16:00"]],
 "faq": [["¿{a} puede diagnosticar un problema?", "No. {a} anota los síntomas y los pasa al mecánico, sin dar nunca un diagnóstico ni un precio de reparación sin tu aprobación."], ["¿Se gestiona el almacenamiento de llantas?", "Sí: {a} anota el almacenamiento, llama a tus clientes antes de la temporada y agenda el cambio."], ["¿Cómo sabe el cliente que su vehículo está listo?", "Cuando está listo, lo marcas en el panel o se lo dices a {a}: sale un mensaje al cliente."]],
 "note": ""
},
"nettoyage": {
 "name": "Empresas de limpieza", "tab": "Limpieza", "aud": "las empresas de limpieza",
 "title": "AI Staff — Asistente con IA para empresas de limpieza",
 "desc": "Presupuestos, limpiezas recurrentes, cambios de horario, reseñas en Google: la asistente con IA de las empresas de limpieza.",
 "eyebrow": "Para empresas de limpieza",
 "h1": "Solicitudes a toda hora. <em>{a} las toma por ti.</em>",
 "lead": "Residencial o comercial, {a} responde las solicitudes, toma los detalles del lugar, da tus precios base y agenda visitas o limpiezas recurrentes — mientras tus equipos están en terreno.",
 "trust": [["24/7", "incluso en la noche"], ["< 10 s", "para contestar"], ["Recurrente", "limpiezas agendadas automáticamente"]],
 "script": [["agent", "Limpieza Éclat, buenos días, habla {a}."], ["lead", "Hola, busco a alguien para una limpieza cada dos semanas."], ["agent", "Con gusto. ¿Es un condominio o una casa, y cuántas habitaciones?"], ["lead", "Un condominio de dos habitaciones en Rosemont."], ["agent", "Para un condominio de dos habitaciones cada dos semanas, son 120 $ por visita. ¿Le propongo una primera limpieza el martes a las 9:00?"], ["lead", "Perfecto."], ["agent", "Queda agendado, cada dos semanas. Le envío la confirmación por mensaje."]],
 "ended": "Limpieza recurrente agendada ✓",
 "fcards": [["phone", "Limpieza cada 2 semanas", "Condominio 2 hab. · Rosemont"], ["googlecalendar", "Horario de equipos", "Equipo B · martes 9:00"], ["stripe", "Pago recibido", "Limpieza de mudanza"]],
 "painH": "Tus equipos están en terreno. Las solicitudes llegan a la oficina.",
 "painP": "Presupuestos, cambios de horario, clientes que quieren agregar una tarea: sin recepcionista, todo pasa por tu celular, muchas veces en medio de una limpieza.",
 "does": ["Responde las solicitudes y da tus precios base", "Agenda limpiezas puntuales y recurrentes según tus equipos", "Gestiona cambios de horario y cancelaciones", "Envía confirmaciones, recordatorios y enlaces de pago"],
 "features": [["🏠", "Residencial", "Limpiezas regulares, limpieza profunda, mudanzas: precios base y reserva."], ["🏢", "Comercial", "Oficinas y comercios: toma de necesidades y visita de evaluación."], ["🔁", "Recurrencia", "Semanal o cada dos semanas, sin reservas duplicadas."], ["⭐", "Reseñas de clientes", "Después de cada limpieza, un mensaje para pedir una reseña en Google."]],
 "steps": [["El cliente escribe o llama", "Teléfono, mensaje, Facebook, Instagram."], ["{a} evalúa la necesidad", "Tipo de lugar, tamaño, frecuencia, extras."], ["Se agenda la limpieza", "En el horario del equipo correcto."], ["El cliente recibe seguimiento", "Recordatorio, pago y solicitud de reseña."]],
 "calc": {"l1": "Solicitudes perdidas por semana", "l2": "Tasa de conversión", "l3": "Valor de un cliente en un año", "disc": "Un cliente regular perdido son decenas de limpiezas menos en el año."},
 "stats": [["Solicitudes recibidas", "24", "esta semana"], ["Limpiezas agendadas", "17", "6 recurrentes"], ["Cambios gestionados", "9", "sin ti"], ["Reseñas pedidas", "15", "después de la limpieza"]],
 "calls": [["Émilie Gagné", "Hoy · 9:02", "Condominio de dos habitaciones, cada dos semanas, Rosemont.", "new", "1.ª limpieza · martes 9:00"], ["Axel Conseil (oficinas)", "Ayer · 15:45", "Limpieza de oficinas 3 noches por semana, 2 500 pi².", "hot", "Visita de evaluación · jueves 17:00"], ["Martin Leclerc", "Ayer · 10:20", "Quiere mover su limpieza del viernes.", "warm", "Movida al lunes 13:00"]],
 "faq": [["¿{a} da precios?", "Sí, si le das tu lista de precios (ej. según el número de habitaciones). Para pedidos especiales, {a} toma los detalles y te los pasa."], ["¿Cómo se gestionan mis equipos?", "Indicas la disponibilidad de cada equipo; {a} agenda en los horarios correctos y evita reservas duplicadas."], ["¿Se pueden pedir reseñas en Google?", "Sí: después de cada limpieza, un mensaje invita al cliente a dejar una reseña."]],
 "note": ""
},
"barbiers": {
 "name": "Barberías y salones", "tab": "Barberías y salones", "aud": "las barberías y los salones",
 "title": "AI Staff — Asistente con IA para barberías y salones",
 "desc": "Citas, DMs de Instagram, cancelaciones y recordatorios: la asistente con IA que contesta mientras cortas.",
 "eyebrow": "Para barberías y salones",
 "h1": "¿Las tijeras en la mano? <em>{a} agenda las citas.</em>",
 "lead": "{a} contesta llamadas y DMs mientras cortas, agenda en el horario de cada barbero, llena las cancelaciones y hace volver a tus clientes regulares.",
 "trust": [["24/7", "incluso con la barbería cerrada"], ["DMs", "Instagram y Facebook"], ["Recordatorios", "menos ausencias"]],
 "script": [["agent", "Barbería Le Classique, ¡hola!, habla {a}."], ["lead", "Hola, ¿tienes espacio para corte y barba hoy?"], ["agent", "Con Max tengo 16:30 o 18:00. Con Sam, 17:15."], ["lead", "Max, a las 18:00."], ["agent", "Perfecto, quedó agendado: corte y barba con Max a las 18:00. Te envío un recordatorio una hora antes."], ["lead", "¡Gracias!"], ["agent", "¡Nos vemos!"]],
 "ended": "Cita agendada ✓",
 "fcards": [["instagram", "DM de Instagram", "Degradado el sábado · agendado"], ["googlecalendar", "Cancelación llenada", "Max · 14:00 · lista de espera"], ["sms", "Recordatorios enviados", "18 clientes · mañana"]],
 "painH": "Estás cortando. Suena el teléfono. No puedes contestar.",
 "painP": "Cada llamada perdida durante un corte es un cliente que reserva en otro lado. Y las ausencias sin aviso dejan huecos en la agenda.",
 "does": ["Contesta llamadas, mensajes y DMs de Instagram mientras cortas", "Agenda según el horario y los servicios de cada barbero", "Llena las cancelaciones con la lista de espera", "Envía recordatorios y hace volver a los clientes regulares"],
 "features": [["✂️", "Cada barbero, su horario", "Servicios, duraciones y disponibilidad propios."], ["📲", "DMs de Instagram", "Los clientes escriben en Instagram: {a} responde y agenda."], ["⏱️", "Cancelaciones", "¿Se libera un espacio? La lista de espera recibe un mensaje."], ["🔁", "Clientes regulares", "«Ya van 4 semanas»: un mensaje para agendar el próximo corte."]],
 "steps": [["El cliente llama o escribe", "Teléfono, mensaje o DM."], ["{a} encuentra el espacio", "Barbero, servicio, hora."], ["Queda agendado", "Con recordatorio automático."], ["El cliente vuelve", "Seguimiento en el momento justo."]],
 "calc": {"l1": "Llamadas y DMs perdidos por semana", "l2": "Tasa de reserva", "l3": "Valor promedio de una visita", "disc": "Un cliente que no puede reservar en segundos reserva en la barbería de al lado."},
 "stats": [["Reservas", "64", "esta semana"], ["DMs respondidos", "38", "Instagram · Facebook"], ["Cancelaciones llenadas", "7", "lista de espera"], ["Recordatorios enviados", "112", "menos ausencias"]],
 "calls": [["Jordan Petit", "Hoy · 10:14", "Corte y barba con Max, hoy.", "new", "Agendado · 18:00"], ["@kev.mtl", "Instagram · ayer 22:00", "Pide un degradado el sábado en la mañana.", "warm", "Agendado · sábado 10:30"], ["Olivier Côté", "Ayer · 13:00", "Cancela su cita de las 14:00.", "cold", "Espacio llenado con la lista de espera"]],
 "faq": [["¿{a} responde los DMs de Instagram?", "Sí, con el plan Completo: {a} responde los DMs, propone horarios y agenda. Activación por fases."], ["¿Cada barbero puede tener su horario?", "Sí: servicios, duraciones, pausas y días libres propios de cada barbero."], ["¿Y si mantengo mi software de reservas?", "{a} puede conectarse según la herramienta (Square, Google Calendar, etc.). Lo confirmamos juntos en la llamada de descubrimiento."]],
 "note": ""
},
"dental": {
 "name": "Clínicas dentales", "tab": "Clínicas dentales", "aud": "las clínicas dentales",
 "title": "AI Staff — Asistente con IA para clínicas dentales",
 "desc": "Citas 24/7, pacientes nuevos, cancelaciones y recordatorios: la asistente con IA que alivia tu recepción.",
 "eyebrow": "Para clínicas dentales",
 "h1": "El teléfono suena en plena limpieza. <em>{a} contesta.</em>",
 "lead": "{a} atiende a los pacientes 24/7, agenda en tus espacios libres, llena las cancelaciones y envía los recordatorios — para que tu recepción respire.",
 "trust": [["24/7", "incluso con la clínica cerrada"], ["< 10 s", "para contestar"], ["Recordatorios", "menos ausencias"]],
 "script": [["agent", "Clínica dental des Érables, buenos días, habla {a}."], ["lead", "Hola, quisiera una limpieza. Ya soy paciente."], ["agent", "Claro. ¿Me da su nombre completo?"], ["lead", "Nathalie Dubois."], ["agent", "Gracias, Nathalie. Tengo el martes a las 14:00 o el jueves a las 9:30 con la higienista."], ["lead", "El martes a las 14:00."], ["agent", "Queda agendado. Le envío una confirmación y un recordatorio dos días antes."]],
 "ended": "Limpieza agendada ✓",
 "fcards": [["phone", "Paciente nuevo", "Examen y limpieza · lunes"], ["googlecalendar", "Cancelación llenada", "Higienista · 11:00"], ["sms", "Recordatorios enviados", "31 pacientes · mañana"]],
 "painH": "Tu recepción no puede estar al teléfono y en el mostrador al mismo tiempo.",
 "painP": "Llamadas durante los tratamientos, recordatorios que toman horas, ausencias que dejan huecos: la recepción corre, y los pacientes cuelgan.",
 "does": ["Atiende a los pacientes 24/7 y agenda en tus espacios libres", "Registra a los pacientes nuevos con la información básica", "Llena las cancelaciones con la lista de espera", "Envía recordatorios y llamados de control"],
 "features": [["🦷", "Pacientes nuevos", "Datos de contacto, seguro, motivo de consulta: expediente listo a su llegada."], ["📅", "Profesionales y horarios", "Dentistas e higienistas, cada uno con sus tipos de cita."], ["🔁", "Llamados de control", "Los pacientes reciben recordatorio en el momento justo para su próxima limpieza."], ["⚕️", "Nunca consejo médico", "Urgencias: {a} aplica tu protocolo y pasa el caso al equipo."]],
 "steps": [["El paciente llama", "Durante los tratamientos, en la noche o el fin de semana."], ["{a} identifica la necesidad", "Limpieza, urgencia, paciente nuevo."], ["Se agenda la cita", "Con el profesional correcto."], ["El paciente recibe recordatorio", "Confirmación, recordatorio y control."]],
 "calc": {"l1": "Llamadas perdidas por semana", "l2": "Tasa de citas agendadas", "l3": "Valor promedio de una cita", "disc": "Un paciente nuevo que cae en el buzón de voz llama a la siguiente clínica."},
 "stats": [["Llamadas atendidas", "73", "esta semana"], ["Citas agendadas", "41", "9 pacientes nuevos"], ["Cancelaciones llenadas", "6", "lista de espera"], ["Recordatorios enviados", "188", "menos ausencias"]],
 "calls": [["Nathalie Dubois", "Hoy · 8:40", "Paciente existente, limpieza.", "new", "Cita · martes 14:00"], ["Youssef Karim", "Ayer · 21:05", "Paciente nuevo, dolor en una muela.", "hot", "Enviado al equipo · llamada 8:00"], ["Claire Martin", "Ayer · 12:30", "Cancela su cita del jueves.", "cold", "Espacio llenado · lista de espera"]],
 "faq": [["¿{a} da consejos médicos?", "Nunca. {a} toma el mensaje, aplica tu protocolo de urgencia (ej. traspaso al equipo) y te pasa la información."], ["¿Se puede conectar con nuestro software de gestión?", "Según el software: confirmamos las opciones en la llamada de descubrimiento. Si no, {a} funciona con un calendario de Google u Outlook."], ["¿Los datos de los pacientes están protegidos?", "Tú eliges qué se conecta y puedes revocar el acceso cuando quieras. Los datos se usan solo para tu clínica y nunca se revenden."]],
 "note": "<b>Salud:</b> {a} nunca da consejos médicos ni hace diagnósticos. Las urgencias siguen el protocolo de tu clínica."
}
}
