# -*- coding: utf-8 -*-
# EN text for sector pages. Numeric fields (calc values, icons, integrations) come from FR.
EN = {
"immobilier": {
 "name": "Real estate brokers", "tab": "Real estate brokers", "aud": "real estate brokers",
 "title": "AI Staff — The AI personal assistant for Québec real estate brokers",
 "desc": "Alex answers during your showings, pre-qualifies buyers, proposes showings and calls you every morning with your day.",
 "eyebrow": "For Québec real estate brokers",
 "h1": "You're at a showing. <em>{a} answers the buyers.</em>",
 "lead": "{a} picks up during your showings, signings and time off, pre-qualifies the buyer, proposes the showing in your calendar — and calls you at 7:30 with your showings, hot leads and follow-ups.",
 "trust": [["24/7", "even during your showings"], ["7:30 AM", "your morning briefing"], ["FR · EN", "and your clients' language"]],
 "script": [["agent", "Marie's office, this is {a}. How can I help?"], ["lead", "Hi, I saw the listing on Saint-Urbain. Is it still available?"], ["agent", "It is! Two bedrooms, 850 sq ft, listed at $649,000. Are you pre-approved, and for how much?"], ["lead", "Yes, up to $700K."], ["agent", "Perfect, that fits well. Marie is free tomorrow at 2 or 4 PM for a showing."], ["lead", "4 PM works."], ["agent", "You're confirmed for tomorrow at 4 PM. I'm texting you the confirmation."]],
 "ended": "Showing confirmed ✓",
 "fcards": [["phone", "Pre-qualified lead", "Pre-approved $700K · Plateau"], ["googlecalendar", "Showing confirmed", "482 Saint-Urbain · 4 PM"], ["gmail", "Draft ready", "Property sheet · to approve"]],
 "painH": "You're at a showing. A buyer calls… the next broker.",
 "painP": "Evenings, weekends, during signings: your phone never sleeps, and every missed call is a buyer finding another broker on Centris.",
 "does": ["Answers during your showings and pre-qualifies: budget, pre-approval, area, timeline", "Proposes showings in your calendar and sends confirmations", "Drafts follow-up emails and property sheets for you to approve", "Calls you at 7:30 with your showings, hot leads and follow-ups"],
 "features": [["🏠", "Pre-qualification", "Budget, pre-approval, area and timeline: you call back knowing the whole file."], ["📅", "Showings", "Slots proposed from your calendar, with confirmation and reminder to the buyer."], ["☀️", "Morning briefing", "Today's showings, overnight leads and follow-ups, by phone."], ["📲", "Call {a}", "“Confirm the 4 PM showing with Sophie”: done, without opening an app."]],
 "steps": [["The buyer calls", "While you're showing, {a} picks up."], ["{a} pre-qualifies", "Budget, pre-approval, area, timeline."], ["The showing is proposed", "In your calendar, with text confirmation."], ["You close", "Summary, transcript and next action in your dashboard."]],
 "calc": {"l1": "Missed calls per week", "l2": "Your showings close at", "l3": "Average commission", "disc": "A missed call isn't just a call: it's a buyer calling the next broker on Centris."},
 "stats": [["Calls handled", "63", "↑ 8 this week"], ["Pre-qualified leads", "32", "↑ 8 this week"], ["Showings booked", "11", "↑ 3 this week"], ["Briefings", "7", "every morning at 7:30"]],
 "calls": [["Julie Tanguay", "Today · 9:12 AM", "Looking for a 3-bedroom near Villeray, pre-approved up to $650K.", "hot", "Showing proposed · Wed 4 PM"], ["Philippe Bergeron", "Yesterday · 4:47 PM", "Selling in Verdun, wants a valuation before listing.", "warm", "Send the valuation report"], ["Mei Kwan", "Yesterday · 11:03 AM", "Browsing the Plateau market, no immediate plans.", "cold", "Follow up in 30 days"]],
 "faq": [["Does {a} give brokerage advice?", "Never. {a} pre-qualifies, takes messages and proposes showings. Any brokerage question goes to you: you keep your professional judgment and control of your files."], ["Does {a} really speak French and English?", "Yes: {a} detects the caller's language and continues in French, English or Spanish, with vocabulary adapted to Québec real estate."], ["Can I call {a} myself?", "Yes, on the Executive plan: {a} recognizes your number. Ask for tomorrow's schedule or have a showing confirmed."]],
 "note": "<b>OACIQ compliance:</b> {a} never gives brokerage advice and never replaces your professional judgment. Every interaction is transcribed and archived: you keep control of your files and client communications, as your ethical obligations require."
},
"cvc": {
 "name": "Heating & cooling (HVAC)", "tab": "HVAC", "aud": "HVAC companies",
 "title": "AI Staff — AI assistant for heating and cooling (HVAC) companies",
 "desc": "24/7 emergencies, seasonal maintenance, quotes: the AI assistant that answers while your technicians are on the road.",
 "eyebrow": "For Québec HVAC companies",
 "h1": "No heat at 2 AM? <em>{a} answers.</em>",
 "lead": "{a} answers emergencies 24/7, triages what can't wait, schedules your maintenance and quotes — and calls you in the morning with your day. In French, English and your clients' language.",
 "trust": [["24/7", "even in a cold snap"], ["< 10 s", "to pick up"], ["Urgent", "forwarded to the on-call technician"]],
 "script": [["agent", "Lavoie Heating, good evening, this is {a}. How can I help?"], ["lead", "My furnace won't start and it's 14 degrees in the house."], ["agent", "I understand. Do you smell gas? Are there children or elderly people in the home?"], ["lead", "No smell. Yes, two kids."], ["agent", "Okay, this is a priority. I'm alerting the on-call technician right now with your address."], ["lead", "Thank you, really."], ["agent", "He'll call you back in the next few minutes. I'm texting you the confirmation."]],
 "ended": "Emergency sent to the technician ✓",
 "fcards": [["phone", "Emergency · Pierrefonds", "Furnace down · technician alerted"], ["googlecalendar", "Maintenance booked", "Heat pump · Thursday 10 AM"], ["sms", "Reminders sent", "Filter change · 42 clients"]],
 "painH": "In winter, every missed call is a client calling your competitor.",
 "painP": "During cold snaps the phone never stops. Your technicians are on the road, the office is swamped, and emergencies get mixed up with quote requests.",
 "does": ["Answers 24/7 and spots real emergencies (no heat, leak, gas smell)", "Forwards urgent calls to the on-call technician, with address and context", "Schedules annual maintenance, installations and quote visits", "Sends maintenance and filter-change reminders"],
 "features": [["🚨", "Emergency triage", "Safety questions, priority level and immediate hand-off to the right technician."], ["🗓️", "Seasonal maintenance", "Reminders before the season: furnaces in the fall, AC and heat pumps in the spring."], ["🧾", "Quotes", "Equipment type, square footage, photos by text: the visit is booked and the file is ready."], ["🌎", "In the client's language", "French, English, Spanish and more: every client is served in their language."]],
 "steps": [["The client calls", "Day, night or storm: {a} picks up in under 10 seconds."], ["{a} qualifies", "Emergency or not, equipment, address, availability."], ["The appointment is booked", "In your technicians' schedule, with text confirmation."], ["You get the summary", "Every morning: overnight emergencies, today's visits, quotes to do."]],
 "calc": {"l1": "Missed calls per week", "l2": "Conversion to a job", "l3": "Average job value", "disc": "An unanswered emergency doesn't call back: it calls the next company on Google."},
 "stats": [["Calls answered", "37", "this week"], ["Emergencies forwarded", "6", "avg. 4 min"], ["Visits booked", "14", "↑ 5 this week"], ["Quotes to do", "5", "complete files"]],
 "calls": [["Julie Tremblay", "Last night · 2:14 AM", "Furnace down, two kids. Forwarded to the on-call technician.", "hot", "Emergency visit · 7:30 AM"], ["Marc Gagnon", "Yesterday · 4:40 PM", "Quote for a wall-mounted heat pump, 1,400 sq ft house.", "warm", "Quote visit · Thursday 1 PM"], ["Nadia Roy", "Yesterday · 11:05 AM", "Annual central AC maintenance.", "new", "Maintenance booked · Oct 3, 9 AM"]],
 "faq": [["Can {a} do a technical diagnosis?", "No. {a} asks the right questions (equipment, symptoms, safety) and passes them to the technician, never giving a diagnosis or repair instructions. If there's a gas smell, {a} asks people to leave and call 911."], ["How are emergencies sent to me?", "By your rules: direct call to the on-call technician, a text with address and summary, or both. Everything else waits for your morning briefing."], ["Is seasonal maintenance handled?", "Yes: {a} calls your clients before the season, offers slots and fills your technicians' schedule."]],
 "note": "<b>Safety:</b> {a} never gives a technical diagnosis. If there's a gas smell or danger, {a} asks people to leave and call 911, then alerts your team."
},
"paysagement": {
 "name": "Landscaping", "tab": "Landscaping", "aud": "landscapers",
 "title": "AI Staff — AI assistant for landscapers",
 "desc": "Quotes, estimate visits, maintenance contracts: the AI assistant that answers while your crews work.",
 "eyebrow": "For Québec landscapers",
 "h1": "You're on a job site. <em>{a} takes the quote requests.</em>",
 "lead": "In spring, requests all come in at once. {a} answers, takes the property details, books estimate visits and follows up with clients — while your crews work.",
 "trust": [["24/7", "even on weekends"], ["< 10 s", "to pick up"], ["Photos", "requested by text"]],
 "script": [["agent", "Vert-Nord Landscaping, hello, this is {a}. How can I help?"], ["lead", "I'd like a quote for interlocking pavers and a flower bed."], ["agent", "Happy to help. What's the address and roughly how many square feet? I'll text you so you can send a few photos."], ["lead", "In Laval, about 400 square feet."], ["agent", "Perfect. Our estimator can come Tuesday at 5 PM or Saturday at 10 AM."], ["lead", "Saturday at 10."], ["agent", "You're booked. You'll get a confirmation and a reminder the day before."]],
 "ended": "Estimate visit booked ✓",
 "fcards": [["phone", "Quote · Laval", "Pavers 400 sq ft · photos received"], ["googlecalendar", "Estimate booked", "Saturday 10 AM · Sainte-Rose"], ["sms", "Follow-ups sent", "12 pending quotes"]],
 "painH": "Spring arrives, and the phone rings while your hands are in the dirt.",
 "painP": "Quote requests pile up in voicemail. The ones who don't get a call back the same day sign with someone else.",
 "does": ["Answers quote requests, even on your busiest job-site days", "Asks for the address, square footage and photos by text", "Books estimate visits in your estimator's schedule", "Follows up with clients who haven't answered the quote"],
 "features": [["📐", "Complete quotes", "Address, project type, size, budget and photos: the estimator shows up prepared."], ["🔁", "Maintenance contracts", "Mowing, seasonal upkeep, openings and closings: reminders and renewals."], ["⛅", "Weather delays", "Clients are texted when a day is postponed because of rain."], ["❄️", "And in winter?", "Do snow removal too? The same number switches to winter contracts."]],
 "steps": [["The client calls or writes", "Phone, text, Facebook or Instagram: {a} answers everywhere."], ["{a} prepares the quote", "Project details, photos and availability."], ["The visit is booked", "In the estimator's schedule, with a reminder the day before."], ["You sign more contracts", "Pending quotes are followed up automatically."]],
 "calc": {"l1": "Missed requests per week", "l2": "Signing rate", "l3": "Average project value", "disc": "In spring, the first company to call back often gets the job."},
 "stats": [["Requests received", "29", "this week"], ["Estimates booked", "11", "↑ 4 this week"], ["Quotes followed up", "12", "3 signed"], ["Photos received", "47", "by text"]],
 "calls": [["Sophie Bélanger", "Today · 8:12 AM", "Pavers and flower bed, about 400 sq ft, Laval.", "hot", "Estimate · Saturday 10 AM"], ["Karim Haddad", "Yesterday · 7:30 PM", "Seasonal mowing contract, corner lot.", "warm", "Quote sent · follow-up Friday"], ["Denis Pelletier", "Yesterday · 1:02 PM", "Pruning two maples, not urgent.", "new", "Callback scheduled · Monday"]],
 "faq": [["Does {a} give prices over the phone?", "Only if you want: you can provide a basic price list (e.g., weekly mowing). For projects, {a} takes the details and books the estimate visit."], ["How are photos received?", "By text: the client replies with photos, which are attached to their request in your dashboard."], ["What about winter?", "If you also do snow removal, the same number handles winter contracts. See the Snow removal page."]],
 "note": ""
},
"deneigement": {
 "name": "Snow removal", "tab": "Snow removal", "aud": "snow removal companies",
 "title": "AI Staff — AI assistant for snow removal companies",
 "desc": "Snowstorm: every call answered, missed driveways flagged, seasonal contracts sold. The snow removal AI assistant.",
 "eyebrow": "For snow removal companies",
 "h1": "Snowstorm? <em>{a} takes every call.</em>",
 "lead": "The morning after a storm, everyone calls at once. {a} answers every client, flags missed driveways, reassures, and sells your seasonal contracts — in French, English and your clients' language.",
 "trust": [["Many", "calls at once, no voicemail"], ["24/7", "even at 5 AM"], ["Text", "alerts before and after the storm"]],
 "script": [["agent", "Boréal Snow Removal, hello, this is {a}."], ["lead", "My driveway wasn't cleared and I have to leave for work!"], ["agent", "Sorry for the wait. What's your address?"], ["lead", "245 des Érables Street, in Longueuil."], ["agent", "Thank you. I'm flagging your address as a priority for the Longueuil crew."], ["lead", "Perfect, thanks."], ["agent", "I'll text you as soon as the crew is on its way."]],
 "ended": "Address flagged to the crew ✓",
 "fcards": [["phone", "Missed driveway · Longueuil", "Flagged to the crew as priority"], ["sms", "Storm alert sent", "All clients notified"], ["stripe", "Seasonal contract paid", "Brossard · 2 payments"]],
 "painH": "The morning after a storm, your phone is jammed.",
 "painP": "Worried clients, missed driveways, new contracts: it all comes at once, often before sunrise. A client who can't reach you doesn't renew next winter.",
 "does": ["Answers every call, even when they come in at the same time", "Records missed driveways and flags them to the right crew", "Sells and renews seasonal contracts, with a payment link", "Sends storm and pass alerts by text"],
 "features": [["📍", "Missed driveways", "Address, area and urgency: sent to the right crew in seconds."], ["📝", "Seasonal contracts", "Pricing by driveway size, payment link and installment reminders."], ["📣", "Client alerts", "A text to your clients before and after the storm: fewer calls, reassured clients."], ["🔁", "Renewals", "At the end of summer, {a} calls your clients to renew before the first snow."]],
 "steps": [["The storm arrives", "{a} alerts your clients by text."], ["Calls come in", "Every call is answered, even at 5 AM."], ["Problems get escalated", "Missed driveways and complaints go to the right crew."], ["Contracts get sold", "New clients and renewals, with online payment."]],
 "calc": {"l1": "Missed calls per week (winter)", "l2": "Conversion to a contract", "l3": "Average seasonal contract", "disc": "A client who couldn't reach you during a storm rarely renews next winter."},
 "stats": [["Calls answered", "186", "during the storm"], ["Driveways flagged", "14", "all resolved"], ["Contracts sold", "9", "↑ 3 this week"], ["Alerts sent", "412", "by text"]],
 "calls": [["Chantal Morin", "This morning · 5:48 AM", "Missed driveway, has to leave for work at 7. Longueuil.", "hot", "Flagged to the crew · priority"], ["Ahmed Benali", "Yesterday · 8:15 PM", "New seasonal contract, double driveway in Brossard.", "new", "Contract sent · 2 payments"], ["Lise Fortin", "Yesterday · 9:30 AM", "Asks if the sidewalk is included.", "warm", "Answer sent · client reassured"]],
 "faq": [["What if everyone calls at the same time?", "{a} can answer several calls simultaneously, with no queue or voicemail. Capacity is adjusted to your volume during activation."], ["Does {a} know my areas and crews?", "Yes: you define your areas and who to contact for each. Missed driveways are sent to the right crew by text."], ["Can contracts be sold online?", "Yes: {a} explains your packages, sends a payment link (Stripe or Square) and confirms the contract."]],
 "note": ""
},
"garages": {
 "name": "Garages & auto repair", "tab": "Garages", "aud": "garages",
 "title": "AI Staff — AI assistant for garages and auto repair shops",
 "desc": "Appointments, tire season, “is my car ready?”: the AI assistant that answers while your mechanics work.",
 "eyebrow": "For garages and repair shops",
 "h1": "Hands in an engine? <em>{a} books the appointment.</em>",
 "lead": "{a} answers while your mechanics work: appointments, tire changes, estimate requests, repair updates — and texts clients when their vehicle is ready.",
 "trust": [["24/7", "even evenings and weekends"], ["< 10 s", "to pick up"], ["Text", "when the vehicle is ready"]],
 "script": [["agent", "Beaulieu Garage, hello, this is {a}."], ["lead", "I'd like to get my winter tires put on."], ["agent", "Of course. What's your vehicle, and do you already have your tires?"], ["lead", "A 2019 Honda Civic, I have my tires."], ["agent", "Perfect. I have Wednesday at 8 AM or Thursday at 3:30 PM."], ["lead", "Thursday at 3:30."], ["agent", "Got it. I'm texting you the confirmation and a reminder the day before."]],
 "ended": "Tire appointment booked ✓",
 "fcards": [["phone", "Tire install · Civic 2019", "Thursday 3:30 PM · confirmed"], ["sms", "Vehicle ready", "Text sent to Mr. Girard"], ["googlecalendar", "Shop schedule", "3 bays free tomorrow morning"]],
 "painH": "Tire season means hundreds of calls in a few weeks.",
 "painP": "While your mechanics work, nobody can answer. Clients hang up, and those waiting for their vehicle call to ask if it's ready.",
 "does": ["Books appointments based on your bays and mechanics", "Handles tire season: installs, storage, reminders", "Answers “Is my car ready?” and texts when it is", "Takes estimate requests with the vehicle and symptoms"],
 "features": [["🛞", "Tire season", "Reminders before the deadline, rapid bookings, storage noted."], ["🔔", "Vehicle ready", "A text to the client when the vehicle is ready: fewer calls to the shop."], ["🧰", "Estimate requests", "Make, model, year, symptoms: the mechanic knows what to expect."], ["🛡️", "No diagnosis", "{a} never gives a mechanical diagnosis: the information goes to the mechanic."]],
 "steps": [["The client calls", "{a} picks up, even when the shop is full."], ["{a} identifies the need", "Vehicle, requested service, urgency."], ["The appointment is booked", "Based on your bays and mechanics."], ["The client stays informed", "Confirmation, reminder, and a text when it's ready."]],
 "calc": {"l1": "Missed calls per week", "l2": "Conversion to appointments", "l3": "Average invoice", "disc": "A client who reaches voicemail calls the garage next door."},
 "stats": [["Calls answered", "52", "this week"], ["Appointments booked", "23", "14 for tires"], ["“Is it ready?”", "18", "answered without you"], ["“Ready” texts", "21", "sent"]],
 "calls": [["Luc Roy", "Today · 7:55 AM", "Winter tire install, 2019 Honda Civic, tires supplied.", "new", "Appointment · Thursday 3:30 PM"], ["Amina Diallo", "Yesterday · 5:20 PM", "Front brake noise, 2017 Toyota RAV4.", "hot", "Inspection · tomorrow 8 AM"], ["Paul Girard", "Yesterday · 12:10 PM", "Asks if his vehicle is ready.", "warm", "Text sent · ready at 4 PM"]],
 "faq": [["Can {a} diagnose a problem?", "No. {a} records the symptoms and passes them to the mechanic, never giving a diagnosis or a repair price without your approval."], ["Is tire storage handled?", "Yes: {a} records storage, calls your clients before the season and books the install."], ["How does the client know the vehicle is ready?", "When it's ready, you mark it in the dashboard or tell {a}: a text goes out to the client."]],
 "note": ""
},
"nettoyage": {
 "name": "Cleaning companies", "tab": "Cleaning", "aud": "cleaning companies",
 "title": "AI Staff — AI assistant for cleaning companies",
 "desc": "Quotes, recurring cleanings, schedule changes, Google reviews: the AI assistant for cleaning companies.",
 "eyebrow": "For cleaning companies",
 "h1": "Requests at all hours. <em>{a} takes them for you.</em>",
 "lead": "Residential or commercial, {a} answers requests, takes the property details, gives your base prices and books visits or recurring cleanings — while your teams are in the field.",
 "trust": [["24/7", "even in the evening"], ["< 10 s", "to pick up"], ["Recurring", "cleanings scheduled automatically"]],
 "script": [["agent", "Éclat Cleaning, hello, this is {a}."], ["lead", "Hi, I'm looking for a cleaning every two weeks."], ["agent", "Happy to help. Is it a condo or a house, and how many bedrooms?"], ["lead", "A two-bedroom condo in Rosemont."], ["agent", "For a two-bedroom condo every two weeks, it's $120 per visit. How about a first cleaning Tuesday at 9 AM?"], ["lead", "Perfect."], ["agent", "You're booked, every two weeks. I'm texting you the confirmation."]],
 "ended": "Recurring cleaning booked ✓",
 "fcards": [["phone", "Every-2-weeks cleaning", "2-bed condo · Rosemont"], ["googlecalendar", "Team schedule", "Team B · Tuesday 9 AM"], ["stripe", "Payment received", "Move-out cleaning"]],
 "painH": "Your teams are in the field. The requests land at the office.",
 "painP": "Quotes, schedule changes, clients who want to add a task: without a receptionist, it all goes through your cell, often in the middle of a cleaning.",
 "does": ["Answers requests and gives your base prices", "Books one-time and recurring cleanings based on your teams", "Handles schedule changes and cancellations", "Sends confirmations, reminders and payment links"],
 "features": [["🏠", "Residential", "Regular cleanings, deep cleans, move-outs: base prices and booking."], ["🏢", "Commercial", "Offices and stores: needs assessment and evaluation visit."], ["🔁", "Recurring", "Weekly or every two weeks, with no double bookings."], ["⭐", "Client reviews", "After each cleaning, a text asking for a Google review."]],
 "steps": [["The client writes or calls", "Phone, text, Facebook, Instagram."], ["{a} assesses the need", "Property type, size, frequency, extras."], ["The cleaning is booked", "In the right team's schedule."], ["The client is followed up", "Reminder, payment and review request."]],
 "calc": {"l1": "Missed requests per week", "l2": "Conversion rate", "l3": "Value of a client over a year", "disc": "One lost regular client means dozens fewer cleanings over the year."},
 "stats": [["Requests received", "24", "this week"], ["Cleanings booked", "17", "6 recurring"], ["Changes handled", "9", "without you"], ["Reviews requested", "15", "after cleaning"]],
 "calls": [["Émilie Gagné", "Today · 9:02 AM", "Two-bedroom condo, every two weeks, Rosemont.", "new", "1st cleaning · Tuesday 9 AM"], ["Axel Conseil (offices)", "Yesterday · 3:45 PM", "Office cleaning 3 evenings a week, 2,500 sq ft.", "hot", "Evaluation visit · Thursday 5 PM"], ["Martin Leclerc", "Yesterday · 10:20 AM", "Wants to move Friday's cleaning.", "warm", "Moved to Monday 1 PM"]],
 "faq": [["Does {a} give prices?", "Yes, if you provide your price list (e.g., by number of bedrooms). For special requests, {a} takes the details and passes them to you."], ["How are my teams managed?", "You set each team's availability; {a} books in the right slots and avoids double bookings."], ["Can we ask for Google reviews?", "Yes: after each cleaning, a text invites the client to leave a review."]],
 "note": ""
},
"barbiers": {
 "name": "Barbers & salons", "tab": "Barbers & salons", "aud": "barbers and salons",
 "title": "AI Staff — AI assistant for barbers and salons",
 "desc": "Appointments, Instagram DMs, cancellations and reminders: the AI assistant that answers while you cut.",
 "eyebrow": "For barbers and salons",
 "h1": "Scissors in hand? <em>{a} books the appointments.</em>",
 "lead": "{a} answers calls and DMs while you cut, books into each barber's schedule, fills cancellations and brings back your regulars.",
 "trust": [["24/7", "even when the shop is closed"], ["DMs", "Instagram and Facebook"], ["Reminders", "fewer no-shows"]],
 "script": [["agent", "Le Classique Barbershop, hey, this is {a}!"], ["lead", "Hey, do you have room for a cut and beard today?"], ["agent", "With Max, I have 4:30 or 6 PM. With Sam, 5:15."], ["lead", "Max, 6 PM."], ["agent", "Perfect, you're booked: cut and beard with Max at 6. I'll send you a reminder an hour before."], ["lead", "Thanks!"], ["agent", "See you soon!"]],
 "ended": "Appointment booked ✓",
 "fcards": [["instagram", "Instagram DM", "Fade on Saturday · booked"], ["googlecalendar", "Cancellation filled", "Max · 2 PM · waitlist"], ["sms", "Reminders sent", "18 clients · tomorrow"]],
 "painH": "You're cutting. The phone rings. You can't answer.",
 "painP": "Every call missed during a cut is a client booking somewhere else. And no-shows leave holes in the schedule.",
 "does": ["Answers calls, texts and Instagram DMs while you cut", "Books based on each barber's schedule and services", "Fills cancellations from the waitlist", "Sends reminders and brings back regulars"],
 "features": [["✂️", "Each barber, their schedule", "Services, durations and availability for each."], ["📲", "Instagram DMs", "Clients write on Instagram: {a} answers and books."], ["⏱️", "Cancellations", "A spot opens up? The waitlist gets a text."], ["🔁", "Regulars", "“It's been 4 weeks”: a text to book the next cut."]],
 "steps": [["The client calls or writes", "Phone, text or DM."], ["{a} finds the spot", "Barber, service, time."], ["It's booked", "With an automatic reminder."], ["The client comes back", "Follow-up at the right time."]],
 "calc": {"l1": "Missed calls and DMs per week", "l2": "Booking rate", "l3": "Average visit value", "disc": "A client who can't book in seconds books at the shop next door."},
 "stats": [["Bookings", "64", "this week"], ["DMs answered", "38", "Instagram · Facebook"], ["Cancellations filled", "7", "waitlist"], ["Reminders sent", "112", "fewer no-shows"]],
 "calls": [["Jordan Petit", "Today · 10:14 AM", "Cut and beard with Max, today.", "new", "Booked · 6 PM"], ["@kev.mtl", "Instagram · yesterday 10 PM", "Wants a fade Saturday morning.", "warm", "Booked · Saturday 10:30 AM"], ["Olivier Côté", "Yesterday · 1:00 PM", "Cancels his 2 PM appointment.", "cold", "Spot filled from the waitlist"]],
 "faq": [["Does {a} answer Instagram DMs?", "Yes, on the Executive plan: {a} answers DMs, offers slots and books. Rolled out in phases."], ["Can each barber have their own schedule?", "Yes: services, durations, breaks and days off for each barber."], ["What if I keep my booking software?", "{a} can connect to it depending on the tool (Square, Google Calendar, etc.). We confirm it together on the discovery call."]],
 "note": ""
},
"dental": {
 "name": "Dental clinics", "tab": "Dental clinics", "aud": "dental clinics",
 "title": "AI Staff — AI assistant for dental clinics",
 "desc": "24/7 appointments, new patients, cancellations and reminders: the AI assistant that frees up your front desk.",
 "eyebrow": "For dental clinics",
 "h1": "The phone rings mid-cleaning. <em>{a} answers.</em>",
 "lead": "{a} answers patients 24/7, books into your open slots, fills cancellations and sends reminders — so your front desk can breathe.",
 "trust": [["24/7", "even when the clinic is closed"], ["< 10 s", "to pick up"], ["Reminders", "fewer no-shows"]],
 "script": [["agent", "Érables Dental Clinic, hello, this is {a}."], ["lead", "Hi, I'd like a cleaning. I'm already a patient."], ["agent", "Of course. May I have your full name?"], ["lead", "Nathalie Dubois."], ["agent", "Thank you, Nathalie. I have Tuesday at 2 PM or Thursday at 9:30 AM with the hygienist."], ["lead", "Tuesday at 2."], ["agent", "You're booked. I'm sending you a confirmation and a reminder two days before."]],
 "ended": "Cleaning booked ✓",
 "fcards": [["phone", "New patient", "Exam and cleaning · Monday"], ["googlecalendar", "Cancellation filled", "Hygienist · 11 AM"], ["sms", "Reminders sent", "31 patients · tomorrow"]],
 "painH": "Your front desk can't be on the phone and at the counter at the same time.",
 "painP": "Calls during treatment, reminders that take hours, no-shows that leave gaps: the front desk runs, and patients hang up.",
 "does": ["Answers patients 24/7 and books into your open slots", "Registers new patients with their basic information", "Fills cancellations from the waitlist", "Sends reminders and recall reminders"],
 "features": [["🦷", "New patients", "Contact details, insurance, reason for visit: the file is ready on arrival."], ["📅", "Practitioners and slots", "Dentists and hygienists, each with their own appointment types."], ["🔁", "Recall reminders", "Patients are reminded at the right time for their next cleaning."], ["⚕️", "Never medical advice", "Emergencies: {a} follows your protocol and passes them to the team."]],
 "steps": [["The patient calls", "During treatment, in the evening or on weekends."], ["{a} identifies the need", "Cleaning, emergency, new patient."], ["The appointment is booked", "With the right practitioner."], ["The patient is reminded", "Confirmation, reminder and recall."]],
 "calc": {"l1": "Missed calls per week", "l2": "Booking rate", "l3": "Average appointment value", "disc": "A new patient who reaches voicemail calls the next clinic."},
 "stats": [["Calls answered", "73", "this week"], ["Appointments booked", "41", "9 new patients"], ["Cancellations filled", "6", "waitlist"], ["Reminders sent", "188", "fewer no-shows"]],
 "calls": [["Nathalie Dubois", "Today · 8:40 AM", "Existing patient, cleaning.", "new", "Appointment · Tuesday 2 PM"], ["Youssef Karim", "Yesterday · 9:05 PM", "New patient, pain in a molar.", "hot", "Sent to the team · callback 8 AM"], ["Claire Martin", "Yesterday · 12:30 PM", "Cancels her Thursday appointment.", "cold", "Spot filled · waitlist"]],
 "faq": [["Does {a} give medical advice?", "Never. {a} takes the message, follows your emergency protocol (e.g., transfer to the team) and passes the information to you."], ["Can it connect to our practice software?", "Depending on the software: we confirm the options on the discovery call. Otherwise, {a} works with a Google or Outlook calendar."], ["Is patient data protected?", "You choose what's connected and can revoke access anytime. Data is used only for your clinic and never resold."]],
 "note": "<b>Health:</b> {a} never gives medical advice and never makes a diagnosis. Emergencies follow your clinic's protocol."
}
}
