# -*- coding: utf-8 -*-
# Contenu FR des pages sectorielles. {a} = nom de l'assistante (Sofía/Alex/Tomás).
# Règle : éviter les pronoms genrés pour {a} (Alex est neutre, Tomás masculin).

FR = {
"immobilier": {
 "persona": "alex",
 "name": "Courtiers immobiliers", "tab": "Courtiers immobiliers", "ic": "🏡", "aud": "les courtiers immobiliers",
 "title": "AI Staff — L'adjoint personnel IA des courtiers immobiliers du Québec",
 "desc": "Alex répond pendant vos visites, pré-qualifie les acheteurs, propose les visites et vous appelle chaque matin avec votre journée.",
 "eyebrow": "Pour les courtiers immobiliers du Québec",
 "h1": "Vous êtes en visite. <em>{a} répond aux acheteurs.</em>",
 "lead": "{a} décroche pendant vos visites, vos signatures et vos congés, pré-qualifie l'acheteur, propose la visite dans votre agenda — et vous appelle à 7 h 30 avec vos visites, vos leads chauds et vos suivis.",
 "trust": [["24/7", "même pendant vos visites"], ["7 h 30", "votre briefing du matin"], ["FR · EN", "et la langue de vos clients"]],
 "script": [["agent", "Bureau de Marie, bonjour, c'est {a}. Comment puis-je vous aider?"], ["lead", "Bonjour, j'ai vu l'inscription sur Saint-Urbain. Elle est toujours disponible?"], ["agent", "Oui! Deux chambres, 850 pi², à 649 000 $. Êtes-vous préapprouvé et pour quel montant?"], ["lead", "Oui, jusqu'à 700 000 $."], ["agent", "Parfait, ça correspond bien. Marie est libre demain à 14 h ou 16 h pour une visite."], ["lead", "16 h, parfait."], ["agent", "C'est confirmé pour demain 16 h. Je vous envoie la confirmation par texto."]],
 "ended": "Visite confirmée ✓",
 "fcards": [["phone", "Lead pré-qualifié", "Préapprouvé 700 k$ · Plateau"], ["googlecalendar", "Visite confirmée", "482, rue Saint-Urbain · 16 h"], ["gmail", "Brouillon prêt", "Fiche de la propriété · à approuver"]],
 "painH": "Vous êtes en visite. Un acheteur appelle… le courtier suivant.",
 "painP": "Les soirs, les fins de semaine, pendant les signatures : votre téléphone ne dort jamais, et chaque appel manqué est un acheteur qui trouve un autre courtier sur Centris.",
 "does": ["Répond pendant vos visites et pré-qualifie : budget, préapprobation, secteur, échéancier", "Propose les visites dans votre agenda et envoie les confirmations", "Prépare les courriels de suivi et les fiches de propriété, que vous approuvez", "Vous appelle à 7 h 30 avec vos visites, vos leads chauds et vos suivis"],
 "features": [["🏠", "Pré-qualification", "Budget, préapprobation, secteur et échéancier : vous rappelez en sachant tout du dossier."], ["📅", "Visites", "Créneaux proposés selon votre agenda, confirmation et rappel à l'acheteur."], ["☀️", "Briefing du matin", "Vos visites du jour, les leads de la nuit et les suivis à faire, au téléphone."], ["📲", "Appelez {a}", "« Confirme la visite de 16 h avec Sophie » : c'est réglé, sans ouvrir une application."]],
 "steps": [["L'acheteur appelle", "Pendant votre visite, {a} décroche."], ["{a} pré-qualifie", "Budget, préapprobation, secteur, échéancier."], ["La visite se propose", "Dans votre agenda, avec confirmation par texto."], ["Vous concluez", "Résumé, transcription et prochaine action dans votre tableau de bord."]],
 "calc": {"l1": "Appels manqués par semaine", "l2": "Vos visites concluent à", "l3": "Commission moyenne", "v": [5, 10, 12000], "r": [[0, 20, 1], [1, 30, 1], [2000, 40000, 500]], "disc": "Un appel manqué n'est pas qu'un appel : c'est un acheteur qui appelle le courtier suivant sur Centris."},
 "stats": [["Appels traités", "63", "↑ 8 cette semaine"], ["Leads pré-qualifiés", "32", "↑ 8 cette semaine"], ["Visites confirmées", "11", "↑ 3 cette semaine"], ["Briefings", "7", "chaque matin 7 h 30"]],
 "calls": [["Julie Tanguay", "Aujourd'hui · 9 h 12", "Cherche un 3 chambres près de Villeray, préapprouvée jusqu'à 650 000 $.", "hot", "Visite proposée · mercredi 16 h"], ["Philippe Bergeron", "Hier · 16 h 47", "Vend à Verdun, souhaite une évaluation avant de s'inscrire.", "warm", "Envoyer le rapport d'évaluation"], ["Mei Kwan", "Hier · 11 h 03", "Curieuse du marché du Plateau, pas de projet immédiat.", "cold", "Suivi dans 30 jours"]],
 "ints": ["googlecalendar", "gmail", "google", "whatsapp", "facebook", "instagram", "zoom", "calendly"],
 "faq": [["Est-ce que {a} donne des conseils en courtage?", "Jamais. {a} pré-qualifie, prend le message et propose la visite. Toute question de courtage vous est transmise : vous gardez votre jugement professionnel et le contrôle de vos dossiers."], ["Est-ce que {a} parle vraiment français et anglais?", "Oui : {a} détecte la langue de l'appelant et continue en français, en anglais ou en espagnol, avec un vocabulaire adapté à l'immobilier québécois."], ["Puis-je appeler {a} moi-même?", "Oui, avec le plan Exécutive : {a} reconnaît votre numéro. Demandez votre horaire du lendemain ou faites confirmer une visite."]],
 "note": "<b>Conformité OACIQ :</b> {a} ne donne jamais de conseils en courtage et ne remplace pas votre jugement professionnel. Chaque interaction est transcrite et archivée : vous gardez le contrôle de vos dossiers et de vos communications clients, comme l'exigent vos obligations déontologiques."
},
"cvc": {
 "name": "Chauffage & climatisation", "tab": "CVC / chauffage", "ic": "🔥", "aud": "les entreprises de chauffage et de climatisation",
 "title": "AI Staff — Adjointe IA pour entreprises de chauffage et climatisation (CVC)",
 "desc": "Urgences 24/7, entretiens saisonniers, soumissions : l'adjointe IA qui répond pendant que vos techniciens sont sur la route.",
 "eyebrow": "Pour les entreprises de CVC du Québec",
 "h1": "Plus de chauffage à 2 h du matin? <em>{a} répond.</em>",
 "lead": "{a} répond aux urgences 24/7, trie ce qui ne peut pas attendre, planifie vos entretiens et vos soumissions — et vous appelle le matin avec votre journée. En français, en anglais et dans la langue de vos clients.",
 "trust": [["24/7", "même en pleine vague de froid"], ["< 10 s", "pour décrocher"], ["Urgent", "transféré au technicien de garde"]],
 "script": [["agent", "Chauffage Lavoie, bonsoir, c'est {a}. Comment puis-je vous aider?"], ["lead", "Ma fournaise ne part plus et il fait 14 degrés dans la maison."], ["agent", "Je comprends. Sentez-vous une odeur de gaz? Y a-t-il des enfants ou des personnes âgées à la maison?"], ["lead", "Pas d'odeur. Oui, deux enfants."], ["agent", "D'accord, c'est prioritaire. J'avertis le technicien de garde tout de suite avec votre adresse."], ["lead", "Merci, vraiment."], ["agent", "Il vous rappelle dans les prochaines minutes. Je vous texte la confirmation."]],
 "ended": "Urgence transmise au technicien ✓",
 "fcards": [["phone", "Urgence · Pierrefonds", "Fournaise en panne · technicien avisé"], ["googlecalendar", "Entretien réservé", "Thermopompe · jeudi 10 h"], ["sms", "Rappels envoyés", "Changement de filtre · 42 clients"]],
 "painH": "L'hiver, chaque appel manqué est un client qui appelle le concurrent.",
 "painP": "Pendant les vagues de froid, le téléphone ne dérougit pas. Vos techniciens sont sur la route, la réception est débordée, et les urgences se mélangent aux demandes de soumission.",
 "does": ["Répond 24/7 et repère les vraies urgences (sans chauffage, fuite, odeur de gaz)", "Transfère l'urgent au technicien de garde, avec l'adresse et le contexte", "Planifie entretiens annuels, installations et visites de soumission", "Envoie les rappels d'entretien et de changement de filtre"],
 "features": [["🚨", "Tri des urgences", "Questions de sécurité, niveau de priorité et transfert immédiat au bon technicien."], ["🗓️", "Entretiens saisonniers", "Rappels avant la saison : fournaises à l'automne, climatiseurs et thermopompes au printemps."], ["🧾", "Soumissions", "Type d'appareil, superficie, photos par texto : la visite est réservée et le dossier est prêt."], ["🌎", "Dans la langue du client", "Français, anglais, espagnol et plus : chaque client est servi dans sa langue."]],
 "steps": [["Le client appelle", "Jour, nuit ou tempête : {a} décroche en moins de 10 secondes."], ["{a} qualifie", "Urgence ou non, type d'appareil, adresse, disponibilités."], ["Le rendez-vous se réserve", "Dans l'horaire de vos techniciens, avec confirmation par texto."], ["Vous recevez le résumé", "Chaque matin : urgences de la nuit, visites du jour, soumissions à faire."]],
 "calc": {"l1": "Appels manqués par semaine", "l2": "Taux de conversion en contrat", "l3": "Valeur moyenne d'un contrat", "v": [8, 35, 450], "r": [[0, 40, 1], [5, 80, 1], [100, 8000, 50]], "disc": "Une urgence sans réponse ne rappelle pas : elle appelle l'entreprise suivante sur Google."},
 "stats": [["Appels répondus", "37", "cette semaine"], ["Urgences transmises", "6", "délai moyen 4 min"], ["Visites réservées", "14", "↑ 5 cette semaine"], ["Soumissions à faire", "5", "dossiers complets"]],
 "calls": [["Julie Tremblay", "Cette nuit · 2 h 14", "Fournaise en panne, deux enfants. Transmis au technicien de garde.", "hot", "Visite d'urgence · 7 h 30"], ["Marc Gagnon", "Hier · 16 h 40", "Soumission pour une thermopompe murale, maison de 1 400 pi².", "warm", "Visite de soumission · jeudi 13 h"], ["Nadia Roy", "Hier · 11 h 05", "Entretien annuel du climatiseur central.", "new", "Entretien réservé · 3 oct. 9 h"]],
 "ints": ["googlecalendar", "gmail", "google", "googlemaps", "quickbooks", "stripe", "square", "whatsapp"],
 "faq": [["Est-ce que {a} peut faire un diagnostic technique?", "Non. {a} pose les bonnes questions (type d'appareil, symptômes, sécurité) et transmet au technicien, sans jamais donner de diagnostic ni d'instruction de réparation. En cas d'odeur de gaz, {a} demande de quitter les lieux et d'appeler le 911."], ["Comment les urgences me sont-elles transmises?", "Selon vos règles : appel direct au technicien de garde, texto avec l'adresse et le résumé, ou les deux. Le reste attend votre briefing du matin."], ["Est-ce que les entretiens saisonniers sont gérés?", "Oui : {a} rappelle vos clients avant la saison, propose des plages et remplit l'horaire de vos techniciens."]],
 "note": "<b>Sécurité :</b> {a} ne pose jamais de diagnostic technique. En cas d'odeur de gaz ou de danger, {a} demande de quitter les lieux et d'appeler le 911, puis avise votre équipe."
},
"paysagement": {
 "name": "Paysagement", "tab": "Paysagement", "ic": "🌿", "aud": "les paysagistes",
 "title": "AI Staff — Adjointe IA pour paysagistes",
 "desc": "Soumissions, visites d'estimation, contrats d'entretien : l'adjointe IA qui répond pendant que vos équipes travaillent.",
 "eyebrow": "Pour les paysagistes du Québec",
 "h1": "Vous êtes sur un chantier. <em>{a} prend les soumissions.</em>",
 "lead": "Au printemps, les demandes arrivent toutes en même temps. {a} répond, prend les détails du terrain, réserve les visites d'estimation et relance les clients — pendant que vos équipes travaillent.",
 "trust": [["24/7", "même la fin de semaine"], ["< 10 s", "pour décrocher"], ["Photos", "demandées par texto"]],
 "script": [["agent", "Paysagement Vert-Nord, bonjour, c'est {a}. Comment puis-je vous aider?"], ["lead", "J'aimerais une soumission pour du pavé uni et une plate-bande."], ["agent", "Avec plaisir. Quelle est l'adresse et environ quelle superficie? Je vous envoie un texto pour recevoir quelques photos."], ["lead", "À Laval, à peu près 400 pieds carrés."], ["agent", "Parfait. Notre estimateur peut passer mardi à 17 h ou samedi à 10 h."], ["lead", "Samedi 10 h."], ["agent", "C'est réservé. Vous recevrez une confirmation et un rappel la veille."]],
 "ended": "Visite d'estimation réservée ✓",
 "fcards": [["phone", "Soumission · Laval", "Pavé uni 400 pi² · photos reçues"], ["googlecalendar", "Estimation réservée", "Samedi 10 h · Sainte-Rose"], ["sms", "Relances envoyées", "12 soumissions en attente"]],
 "painH": "Le printemps arrive, et le téléphone sonne pendant que vous êtes dans la terre.",
 "painP": "Les demandes de soumission s'accumulent dans la boîte vocale. Ceux qui ne sont pas rappelés dans la journée signent avec quelqu'un d'autre.",
 "does": ["Répond aux demandes de soumission, même pendant vos journées sur les chantiers", "Demande l'adresse, la superficie et des photos par texto", "Réserve les visites d'estimation dans l'horaire de l'estimateur", "Relance les clients qui n'ont pas répondu à la soumission"],
 "features": [["📐", "Soumissions complètes", "Adresse, type de projet, superficie, budget et photos : l'estimateur arrive préparé."], ["🔁", "Contrats d'entretien", "Tonte, entretien saisonnier, ouverture et fermeture : rappels et renouvellements."], ["⛅", "Météo et reports", "Vos clients sont avisés par texto quand une journée est reportée à cause de la pluie."], ["❄️", "Et l'hiver?", "Vous faites aussi du déneigement? Le même numéro passe aux contrats d'hiver."]],
 "steps": [["Le client appelle ou écrit", "Téléphone, texto, Facebook ou Instagram : {a} répond partout."], ["{a} prépare la soumission", "Détails du projet, photos et disponibilités."], ["La visite se réserve", "Dans l'horaire de l'estimateur, avec rappel la veille."], ["Vous signez plus de contrats", "Les soumissions en attente sont relancées automatiquement."]],
 "calc": {"l1": "Demandes manquées par semaine", "l2": "Taux de signature", "l3": "Valeur moyenne d'un projet", "v": [6, 30, 3500], "r": [[0, 30, 1], [5, 70, 1], [300, 30000, 100]], "disc": "Au printemps, la première entreprise qui rappelle obtient souvent le contrat."},
 "stats": [["Demandes reçues", "29", "cette semaine"], ["Estimations réservées", "11", "↑ 4 cette semaine"], ["Soumissions relancées", "12", "3 signées"], ["Photos reçues", "47", "par texto"]],
 "calls": [["Sophie Bélanger", "Aujourd'hui · 8 h 12", "Pavé uni et plate-bande, environ 400 pi², Laval.", "hot", "Estimation · samedi 10 h"], ["Karim Haddad", "Hier · 19 h 30", "Contrat de tonte pour la saison, terrain de coin.", "warm", "Soumission envoyée · relance vendredi"], ["Denis Pelletier", "Hier · 13 h 02", "Élagage de deux érables, pas urgent.", "new", "Rappel planifié · lundi"]],
 "ints": ["googlecalendar", "gmail", "google", "facebook", "instagram", "quickbooks", "stripe", "whatsapp"],
 "faq": [["Est-ce que {a} donne des prix au téléphone?", "Seulement si vous le souhaitez : vous pouvez fournir une grille de base (ex. tonte hebdomadaire). Pour les projets, {a} prend les détails et réserve la visite d'estimation."], ["Comment les photos sont-elles reçues?", "Par texto : le client répond avec ses photos, qui sont jointes à sa demande dans votre tableau de bord."], ["Et pendant l'hiver?", "Si vous faites aussi du déneigement, le même numéro sert aux contrats d'hiver. Voyez la page Déneigement."]],
 "note": ""
},
"deneigement": {
 "name": "Déneigement", "tab": "Déneigement", "ic": "❄️", "aud": "les entreprises de déneigement",
 "title": "AI Staff — Adjointe IA pour entreprises de déneigement",
 "desc": "Tempête de neige : tous les appels répondus, entrées oubliées signalées, contrats de saison vendus. L'adjointe IA du déneigement.",
 "eyebrow": "Pour les entreprises de déneigement",
 "h1": "Tempête de neige? <em>{a} prend tous les appels.</em>",
 "lead": "Le lendemain d'une tempête, tout le monde appelle en même temps. {a} répond à chaque client, signale les entrées oubliées, rassure, et vend vos contrats de saison — en français, en anglais et dans la langue de vos clients.",
 "trust": [["Plusieurs", "appels en même temps, sans boîte vocale"], ["24/7", "même à 5 h du matin"], ["Texto", "alertes avant et après la tempête"]],
 "script": [["agent", "Déneigement Boréal, bonjour, c'est {a}."], ["lead", "Mon entrée n'a pas été déneigée et je dois partir travailler!"], ["agent", "Désolé pour l'attente. Quelle est votre adresse?"], ["lead", "Le 245, rue des Érables, à Longueuil."], ["agent", "Merci. Je signale votre adresse en priorité à l'équipe de Longueuil."], ["lead", "Parfait, merci."], ["agent", "Je vous texte dès que l'équipe est en route."]],
 "ended": "Adresse signalée à l'équipe ✓",
 "fcards": [["phone", "Entrée oubliée · Longueuil", "Signalée à l'équipe en priorité"], ["sms", "Alerte tempête envoyée", "Tous les clients avisés"], ["stripe", "Contrat de saison payé", "Brossard · 2 versements"]],
 "painH": "Le lendemain d'une tempête, votre téléphone est saturé.",
 "painP": "Clients inquiets, entrées oubliées, nouveaux contrats : tout arrive en même temps, souvent avant le lever du soleil. Un client sans réponse ne renouvelle pas l'hiver suivant.",
 "does": ["Répond à tous les appels, même quand ils arrivent en même temps", "Note les entrées oubliées et les signale à la bonne équipe", "Vend et renouvelle les contrats de saison, avec lien de paiement", "Envoie des alertes de tempête et de passage par texto"],
 "features": [["📍", "Entrées oubliées", "Adresse, secteur et urgence : transmis à l'équipe concernée en quelques secondes."], ["📝", "Contrats de saison", "Prix selon la grandeur de l'entrée, lien de paiement et rappels de versement."], ["📣", "Alertes aux clients", "Un texto à vos clients avant et après la tempête : moins d'appels, clients rassurés."], ["🔁", "Renouvellements", "À la fin de l'été, {a} rappelle vos clients pour renouveler avant la première neige."]],
 "steps": [["La tempête arrive", "{a} avertit vos clients par texto."], ["Les appels entrent", "Chaque appel reçoit une réponse, même à 5 h du matin."], ["Les problèmes remontent", "Entrées oubliées et plaintes vont à la bonne équipe."], ["Les contrats se vendent", "Nouveaux clients et renouvellements, avec paiement en ligne."]],
 "calc": {"l1": "Appels manqués par semaine (en hiver)", "l2": "Taux de conversion en contrat", "l3": "Valeur moyenne d'un contrat de saison", "v": [15, 25, 650], "r": [[0, 80, 1], [5, 70, 1], [200, 3000, 25]], "disc": "Un client qui n'a pas pu vous joindre pendant une tempête renouvelle rarement l'hiver suivant."},
 "stats": [["Appels répondus", "186", "pendant la tempête"], ["Entrées signalées", "14", "toutes réglées"], ["Contrats vendus", "9", "↑ 3 cette semaine"], ["Alertes envoyées", "412", "par texto"]],
 "calls": [["Chantal Morin", "Ce matin · 5 h 48", "Entrée oubliée, doit partir travailler à 7 h. Longueuil.", "hot", "Signalée à l'équipe · priorité"], ["Ahmed Benali", "Hier · 20 h 15", "Nouveau contrat de saison, entrée double à Brossard.", "new", "Contrat envoyé · 2 versements"], ["Lise Fortin", "Hier · 9 h 30", "Demande si le trottoir est inclus.", "warm", "Réponse envoyée · client rassuré"]],
 "ints": ["googlecalendar", "gmail", "stripe", "square", "quickbooks", "googlemaps", "facebook", "whatsapp"],
 "faq": [["Et si tout le monde appelle en même temps?", "{a} peut répondre à plusieurs appels simultanément, sans file d'attente ni boîte vocale. La capacité est ajustée à votre volume lors de l'activation."], ["Est-ce que {a} connaît mes secteurs et mes équipes?", "Oui : vous définissez vos secteurs et qui contacter pour chacun. Les entrées oubliées sont transmises à la bonne équipe par texto."], ["Peut-on vendre les contrats en ligne?", "Oui : {a} explique vos forfaits, envoie un lien de paiement (Stripe ou Square) et confirme le contrat."]],
 "note": ""
},
"garages": {
 "name": "Garages & mécanique", "tab": "Garages", "ic": "🔧", "aud": "les garages",
 "title": "AI Staff — Adjointe IA pour garages et ateliers de mécanique",
 "desc": "Rendez-vous, saison des pneus, « est-ce que mon auto est prête? » : l'adjointe IA qui répond pendant que vos mécaniciens travaillent.",
 "eyebrow": "Pour les garages et ateliers",
 "h1": "Les mains dans un moteur? <em>{a} prend le rendez-vous.</em>",
 "lead": "{a} répond pendant que vos mécaniciens travaillent : rendez-vous, changements de pneus, demandes d'estimation, suivi des réparations — et texte les clients quand leur véhicule est prêt.",
 "trust": [["24/7", "même le soir et la fin de semaine"], ["< 10 s", "pour décrocher"], ["Texto", "quand le véhicule est prêt"]],
 "script": [["agent", "Garage Beaulieu, bonjour, c'est {a}."], ["lead", "Je voudrais faire poser mes pneus d'hiver."], ["agent", "Bien sûr. Quel est votre véhicule, et avez-vous déjà vos pneus?"], ["lead", "Une Honda Civic 2019, j'ai mes pneus."], ["agent", "Parfait. J'ai mercredi à 8 h ou jeudi à 15 h 30."], ["lead", "Jeudi 15 h 30."], ["agent", "C'est noté. Je vous texte la confirmation et un rappel la veille."]],
 "ended": "Rendez-vous pneus réservé ✓",
 "fcards": [["phone", "Pose de pneus · Civic 2019", "Jeudi 15 h 30 · confirmé"], ["sms", "Véhicule prêt", "Texto envoyé à M. Girard"], ["googlecalendar", "Horaire de l'atelier", "3 baies libres demain matin"]],
 "painH": "La saison des pneus, c'est des centaines d'appels en quelques semaines.",
 "painP": "Pendant que vos mécaniciens travaillent, personne ne peut répondre. Les clients raccrochent, et ceux qui attendent leur véhicule appellent pour savoir s'il est prêt.",
 "does": ["Prend les rendez-vous selon la disponibilité de vos baies et de vos mécaniciens", "Gère la saison des pneus : pose, entreposage, rappels", "Répond aux « Est-ce que mon auto est prête? » et texte quand elle l'est", "Prend les demandes d'estimation avec le véhicule et les symptômes"],
 "features": [["🛞", "Saison des pneus", "Rappels avant la date limite, réservations en rafale, entreposage noté."], ["🔔", "Véhicule prêt", "Un texto au client quand le véhicule est prêt : moins d'appels à l'atelier."], ["🧰", "Demandes d'estimation", "Marque, modèle, année, symptômes : le mécanicien sait à quoi s'attendre."], ["🛡️", "Pas de diagnostic", "{a} ne pose jamais de diagnostic mécanique : l'information va au mécanicien."]],
 "steps": [["Le client appelle", "{a} décroche, même quand l'atelier est plein."], ["{a} identifie le besoin", "Véhicule, service demandé, urgence."], ["Le rendez-vous se réserve", "Selon vos baies et vos mécaniciens."], ["Le client est tenu au courant", "Confirmation, rappel, et texto quand c'est prêt."]],
 "calc": {"l1": "Appels manqués par semaine", "l2": "Taux de conversion en rendez-vous", "l3": "Facture moyenne", "v": [12, 50, 380], "r": [[0, 60, 1], [5, 90, 1], [50, 3000, 10]], "disc": "Un client qui tombe sur la boîte vocale appelle le garage d'à côté."},
 "stats": [["Appels répondus", "52", "cette semaine"], ["Rendez-vous pris", "23", "dont 14 pour des pneus"], ["« Est-ce prêt? »", "18", "répondus sans vous"], ["Textos « prêt »", "21", "envoyés"]],
 "calls": [["Luc Roy", "Aujourd'hui · 7 h 55", "Pose de pneus d'hiver, Honda Civic 2019, pneus fournis.", "new", "Rendez-vous · jeudi 15 h 30"], ["Amina Diallo", "Hier · 17 h 20", "Bruit de freins à l'avant, Toyota RAV4 2017.", "hot", "Inspection · demain 8 h"], ["Paul Girard", "Hier · 12 h 10", "Demande si son véhicule est prêt.", "warm", "Texto envoyé · prêt à 16 h"]],
 "ints": ["googlecalendar", "gmail", "google", "googlemaps", "quickbooks", "square", "stripe", "whatsapp"],
 "faq": [["Est-ce que {a} peut diagnostiquer un problème?", "Non. {a} note les symptômes et les transmet au mécanicien, sans jamais poser de diagnostic ni donner de prix de réparation sans votre accord."], ["Est-ce que l'entreposage des pneus est géré?", "Oui : {a} note l'entreposage, rappelle vos clients avant la saison et réserve la pose."], ["Comment le client sait-il que son véhicule est prêt?", "Quand le véhicule est prêt, vous le marquez dans le tableau de bord ou vous le dites à {a} : un texto part au client."]],
 "note": ""
},
"nettoyage": {
 "name": "Entreprises de nettoyage", "tab": "Nettoyage", "ic": "🧽", "aud": "les entreprises de nettoyage",
 "title": "AI Staff — Adjointe IA pour entreprises de nettoyage",
 "desc": "Soumissions, ménages récurrents, changements d'horaire, avis Google : l'adjointe IA des entreprises de nettoyage.",
 "eyebrow": "Pour les entreprises de nettoyage",
 "h1": "Des demandes à toute heure. <em>{a} les prend pour vous.</em>",
 "lead": "Résidentiel ou commercial, {a} répond aux demandes, prend les détails du lieu, donne vos prix de base et réserve les visites ou les ménages récurrents — pendant que vos équipes sont sur le terrain.",
 "trust": [["24/7", "même le soir"], ["< 10 s", "pour décrocher"], ["Récurrent", "ménages planifiés automatiquement"]],
 "script": [["agent", "Nettoyage Éclat, bonjour, c'est {a}."], ["lead", "Bonjour, je cherche quelqu'un pour un ménage aux deux semaines."], ["agent", "Avec plaisir. C'est pour un condo ou une maison, et combien de chambres?"], ["lead", "Un condo de deux chambres à Rosemont."], ["agent", "Pour un condo de deux chambres aux deux semaines, c'est 120 $ par visite. Je vous propose un premier ménage mardi à 9 h?"], ["lead", "Parfait."], ["agent", "C'est réservé, aux deux semaines. Je vous envoie la confirmation par texto."]],
 "ended": "Ménage récurrent réservé ✓",
 "fcards": [["phone", "Ménage aux 2 semaines", "Condo 2 ch. · Rosemont"], ["googlecalendar", "Horaire des équipes", "Équipe B · mardi 9 h"], ["stripe", "Paiement reçu", "Ménage de fin de bail"]],
 "painH": "Vos équipes sont sur le terrain. Les demandes, elles, arrivent au bureau.",
 "painP": "Soumissions, changements d'horaire, clients qui veulent ajouter une tâche : sans réceptionniste, tout passe par votre cellulaire, souvent pendant un ménage.",
 "does": ["Répond aux demandes et donne vos prix de base", "Réserve les ménages ponctuels et récurrents selon vos équipes", "Gère les changements d'horaire et les annulations", "Envoie confirmations, rappels et liens de paiement"],
 "features": [["🏠", "Résidentiel", "Ménages réguliers, grand ménage, fin de bail : prix de base et réservation."], ["🏢", "Commercial", "Bureaux et commerces : prise de besoins et visite d'évaluation."], ["🔁", "Récurrence", "Aux semaines ou aux deux semaines, sans double réservation."], ["⭐", "Avis clients", "Après chaque ménage, un texto pour demander un avis Google."]],
 "steps": [["Le client écrit ou appelle", "Téléphone, texto, Facebook, Instagram."], ["{a} évalue le besoin", "Type de lieu, taille, fréquence, extras."], ["Le ménage se réserve", "Dans l'horaire de la bonne équipe."], ["Le client est suivi", "Rappel, paiement et demande d'avis."]],
 "calc": {"l1": "Demandes manquées par semaine", "l2": "Taux de conversion", "l3": "Valeur d'un client sur un an", "v": [5, 40, 2400], "r": [[0, 30, 1], [5, 90, 1], [100, 20000, 100]], "disc": "Un client régulier perdu, c'est des dizaines de ménages en moins sur l'année."},
 "stats": [["Demandes reçues", "24", "cette semaine"], ["Ménages réservés", "17", "dont 6 récurrents"], ["Changements gérés", "9", "sans vous"], ["Avis demandés", "15", "après ménage"]],
 "calls": [["Émilie Gagné", "Aujourd'hui · 9 h 02", "Condo de deux chambres, ménage aux deux semaines, Rosemont.", "new", "1er ménage · mardi 9 h"], ["Axel Conseil (bureaux)", "Hier · 15 h 45", "Nettoyage de bureaux 3 soirs par semaine, 2 500 pi².", "hot", "Visite d'évaluation · jeudi 17 h"], ["Martin Leclerc", "Hier · 10 h 20", "Veut déplacer son ménage de vendredi.", "warm", "Déplacé à lundi 13 h"]],
 "ints": ["googlecalendar", "gmail", "google", "stripe", "square", "quickbooks", "facebook", "whatsapp"],
 "faq": [["Est-ce que {a} donne des prix?", "Oui, si vous fournissez votre grille (ex. selon le nombre de chambres). Pour les demandes particulières, {a} prend les détails et vous les transmet."], ["Comment mes équipes sont-elles gérées?", "Vous indiquez les disponibilités de chaque équipe; {a} réserve dans les bonnes plages et évite les doubles réservations."], ["Peut-on demander des avis Google?", "Oui : après chaque ménage, un texto invite le client à laisser un avis."]],
 "note": ""
},
"barbiers": {
 "name": "Salons & barbiers", "tab": "Barbiers & salons", "ic": "💈", "aud": "les salons et les barbiers",
 "title": "AI Staff — Adjointe IA pour barbiers et salons",
 "desc": "Rendez-vous, DM Instagram, annulations et rappels : l'adjointe IA qui répond pendant que vous coupez.",
 "eyebrow": "Pour les barbiers et les salons",
 "h1": "Les ciseaux dans les mains? <em>{a} prend les rendez-vous.</em>",
 "lead": "{a} répond aux appels et aux DM pendant que vous coupez, réserve dans l'horaire de chaque barbier, remplit les annulations et rappelle vos clients réguliers.",
 "trust": [["24/7", "même quand le salon est fermé"], ["DM", "Instagram et Facebook"], ["Rappels", "moins d'absences"]],
 "script": [["agent", "Barbier Le Classique, salut, c'est {a}!"], ["lead", "Salut, as-tu de la place pour une coupe et barbe aujourd'hui?"], ["agent", "Avec Max, j'ai 16 h 30 ou 18 h. Avec Sam, 17 h 15."], ["lead", "Max, 18 h."], ["agent", "Parfait, c'est réservé : coupe et barbe avec Max à 18 h. Je t'envoie un rappel une heure avant."], ["lead", "Merci!"], ["agent", "À tantôt!"]],
 "ended": "Rendez-vous réservé ✓",
 "fcards": [["instagram", "DM Instagram", "Dégradé samedi · réservé"], ["googlecalendar", "Annulation remplie", "Max · 14 h · liste d'attente"], ["sms", "Rappels envoyés", "18 clients · demain"]],
 "painH": "Vous coupez. Le téléphone sonne. Vous ne pouvez pas répondre.",
 "painP": "Chaque appel manqué pendant une coupe, c'est un client qui réserve ailleurs. Et les absences sans avertissement laissent des trous dans l'horaire.",
 "does": ["Répond aux appels, textos et DM Instagram pendant que vous coupez", "Réserve selon l'horaire et les services de chaque barbier", "Remplit les annulations avec la liste d'attente", "Envoie les rappels et relance les clients réguliers"],
 "features": [["✂️", "Chaque barbier, son horaire", "Services, durées et disponibilités propres à chacun."], ["📲", "DM Instagram", "Les clients écrivent sur Instagram : {a} répond et réserve."], ["⏱️", "Annulations", "Une place se libère? La liste d'attente reçoit un texto."], ["🔁", "Clients réguliers", "« Ça fait 4 semaines » : un texto pour réserver la prochaine coupe."]],
 "steps": [["Le client appelle ou écrit", "Téléphone, texto ou DM."], ["{a} trouve la place", "Barbier, service, heure."], ["C'est réservé", "Avec rappel automatique."], ["Le client revient", "Relance au bon moment."]],
 "calc": {"l1": "Appels et DM manqués par semaine", "l2": "Taux de réservation", "l3": "Valeur moyenne d'une visite", "v": [15, 60, 40], "r": [[0, 80, 1], [10, 100, 1], [15, 200, 1]], "disc": "Un client qui ne peut pas réserver en quelques secondes réserve au salon d'à côté."},
 "stats": [["Réservations", "64", "cette semaine"], ["DM répondus", "38", "Instagram · Facebook"], ["Annulations remplies", "7", "liste d'attente"], ["Rappels envoyés", "112", "moins d'absences"]],
 "calls": [["Jordan Petit", "Aujourd'hui · 10 h 14", "Coupe et barbe avec Max, aujourd'hui.", "new", "Réservé · 18 h"], ["@kev.mtl", "Instagram · hier 22 h", "Demande un dégradé samedi matin.", "warm", "Réservé · samedi 10 h 30"], ["Olivier Côté", "Hier · 13 h 00", "Annule son rendez-vous de 14 h.", "cold", "Place remplie par la liste d'attente"]],
 "ints": ["googlecalendar", "instagram", "facebook", "messenger", "square", "stripe", "google", "whatsapp"],
 "faq": [["Est-ce que {a} répond aux DM Instagram?", "Oui, avec le plan Exécutive : {a} répond aux DM, propose des plages et réserve. Activation par phases."], ["Chaque barbier peut-il avoir son horaire?", "Oui : services, durées, pauses et jours de congé propres à chaque barbier."], ["Et si je garde mon logiciel de réservation?", "{a} peut s'y brancher selon l'outil (Square, Google Agenda, etc.). On le confirme ensemble lors de l'appel découverte."]],
 "note": ""
},
"dental": {
 "name": "Cliniques dentaires", "tab": "Cliniques dentaires", "ic": "🦷", "aud": "les cliniques dentaires",
 "title": "AI Staff — Adjointe IA pour cliniques dentaires",
 "desc": "Rendez-vous 24/7, nouveaux patients, annulations et rappels : l'adjointe IA qui soulage votre réception.",
 "eyebrow": "Pour les cliniques dentaires",
 "h1": "Le téléphone sonne en plein détartrage. <em>{a} répond.</em>",
 "lead": "{a} répond aux patients 24/7, prend les rendez-vous dans vos plages libres, remplit les annulations et envoie les rappels — pour que votre réception respire.",
 "trust": [["24/7", "même la clinique fermée"], ["< 10 s", "pour décrocher"], ["Rappels", "moins d'absences"]],
 "script": [["agent", "Clinique dentaire des Érables, bonjour, c'est {a}."], ["lead", "Bonjour, je voudrais un nettoyage. Je suis déjà patiente."], ["agent", "Bien sûr. Puis-je avoir votre nom complet?"], ["lead", "Nathalie Dubois."], ["agent", "Merci, Nathalie. J'ai mardi à 14 h ou jeudi à 9 h 30 avec l'hygiéniste."], ["lead", "Mardi 14 h."], ["agent", "C'est réservé. Je vous envoie une confirmation et un rappel deux jours avant."]],
 "ended": "Nettoyage réservé ✓",
 "fcards": [["phone", "Nouveau patient", "Examen et nettoyage · lundi"], ["googlecalendar", "Annulation remplie", "Hygiéniste · 11 h"], ["sms", "Rappels envoyés", "31 patients · demain"]],
 "painH": "Votre réception ne peut pas être au téléphone et au comptoir en même temps.",
 "painP": "Appels pendant les soins, rappels qui prennent des heures, absences qui laissent des trous : la réception court, et des patients raccrochent.",
 "does": ["Répond aux patients 24/7 et prend les rendez-vous dans vos plages libres", "Inscrit les nouveaux patients avec les informations de base", "Remplit les annulations avec la liste d'attente", "Envoie les rappels et les rappels de suivi"],
 "features": [["🦷", "Nouveaux patients", "Coordonnées, assurance, motif de consultation : dossier prêt à l'arrivée."], ["📅", "Praticiens et plages", "Dentistes et hygiénistes, chacun avec ses types de rendez-vous."], ["🔁", "Rappels de suivi", "Les patients sont rappelés au bon moment pour leur prochain nettoyage."], ["⚕️", "Jamais de conseil médical", "Urgences : {a} applique votre protocole et transmet à l'équipe."]],
 "steps": [["Le patient appelle", "Pendant les soins, le soir ou la fin de semaine."], ["{a} identifie le besoin", "Nettoyage, urgence, nouveau patient."], ["Le rendez-vous se réserve", "Avec le bon praticien."], ["Le patient est rappelé", "Confirmation, rappel et suivi."]],
 "calc": {"l1": "Appels manqués par semaine", "l2": "Taux de prise de rendez-vous", "l3": "Valeur moyenne d'un rendez-vous", "v": [10, 60, 180], "r": [[0, 60, 1], [10, 100, 1], [50, 1500, 10]], "disc": "Un nouveau patient qui tombe sur la boîte vocale appelle la clinique suivante."},
 "stats": [["Appels répondus", "73", "cette semaine"], ["Rendez-vous pris", "41", "dont 9 nouveaux patients"], ["Annulations remplies", "6", "liste d'attente"], ["Rappels envoyés", "188", "moins d'absences"]],
 "calls": [["Nathalie Dubois", "Aujourd'hui · 8 h 40", "Patiente existante, nettoyage.", "new", "Rendez-vous · mardi 14 h"], ["Youssef Karim", "Hier · 21 h 05", "Nouveau patient, douleur à une molaire.", "hot", "Transmis à l'équipe · rappel 8 h"], ["Claire Martin", "Hier · 12 h 30", "Annule son rendez-vous de jeudi.", "cold", "Place remplie · liste d'attente"]],
 "ints": ["googlecalendar", "gmail", "google", "stripe", "square", "facebook", "whatsapp"],
 "faq": [["Est-ce que {a} donne des conseils médicaux?", "Jamais. {a} prend le message, applique votre protocole d'urgence (ex. transfert à l'équipe) et vous transmet l'information."], ["Peut-on se connecter à notre logiciel de gestion?", "Selon le logiciel : on confirme les options lors de l'appel découverte. Sinon, {a} fonctionne avec un agenda Google ou Outlook."], ["Les données des patients sont-elles protégées?", "Vous choisissez ce qui est connecté et vous pouvez révoquer l'accès en tout temps. Les données servent uniquement à votre clinique et ne sont jamais revendues."]],
 "note": "<b>Santé :</b> {a} ne donne jamais de conseil médical et n'établit aucun diagnostic. Les urgences suivent le protocole de votre clinique."
}
}
